In [1]:
import os
import sys
import csv
import argparse
import psycopg2
import pandas as pd
from psycopg2 import sql
from dotenv import load_dotenv
import csv
from psycopg2.extras import RealDictCursor
# Load .env from project root
load_dotenv()

True

# Connect database

In [2]:
# Env keys (fallbacks)
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "postgres")
DB_USER = os.getenv("DB_USER", "")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")
CONNECT_TIMEOUT = int(os.getenv("DB_CONNECT_TIMEOUT", "10"))

In [3]:
def get_db_connection():
    """
    Trả về psycopg2 connection sử dụng biến môi trường từ .env.
    """
    conn_kwargs = {
        "host": DB_HOST,
        "port": DB_PORT,
        "dbname": DB_NAME,
        "user": DB_USER,
        "password": DB_PASSWORD,
        "connect_timeout": CONNECT_TIMEOUT,
    }
    return psycopg2.connect(cursor_factory=RealDictCursor, **conn_kwargs)

def test_connection(sql_query: str = "SELECT now() AS now"):
    """
    Thực thi 1 câu SQL test và in kết quả.
    """
    conn = None
    try:
        conn = get_db_connection()
        with conn.cursor() as cur:
            cur.execute(sql_query)
            rows = cur.fetchall()
            print(f"✓ Query executed: {sql_query}")
            for row in rows:
                print(row)
    except Exception as e:
        print(f"DB error: {e}")
    finally:
        if conn:
            conn.close()

def list_tables():
    """Liệt kê các bảng hiện có (bỏ schema hệ thống)."""
    sql_query = """
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_type='BASE TABLE'
      AND table_schema NOT IN ('pg_catalog','information_schema')
    ORDER BY table_schema, table_name;
    """
    test_connection(sql_query)

In [4]:
list_tables()

✓ Query executed:
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_type='BASE TABLE'
      AND table_schema NOT IN ('pg_catalog','information_schema')
    ORDER BY table_schema, table_name;

RealDictRow([('table_schema', 'public'), ('table_name', 'Action')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Admin')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Answer')])
RealDictRow([('table_schema', 'public'), ('table_name', 'AnswerTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Attachment')])
RealDictRow([('table_schema', 'public'), ('table_name', 'AttachmentReference')])
RealDictRow([('table_schema', 'public'), ('table_name', 'BiometricDevice')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Category')])
RealDictRow([('table_schema', 'public'), ('table_name', 'CategoryOpenTime')])
RealDictRow([('table_schema', 'public'), ('table_name', 'CategoryOpenTimeTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'CategoryTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'City')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Content')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ContentMascot')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ContentMascotMedia')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ContentTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Gallery')])
RealDictRow([('table_schema', 'public'), ('table_name', 'GalleryTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Home')])
RealDictRow([('table_schema', 'public'), ('table_name', 'HomeTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Itinerary')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ItineraryPlace')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Notification')])
RealDictRow([('table_schema', 'public'), ('table_name', 'NotificationHistory')])
RealDictRow([('table_schema', 'public'), ('table_name', 'OTP')])
RealDictRow([('table_schema', 'public'), ('table_name', 'PhotoStory')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Plan')])
RealDictRow([('table_schema', 'public'), ('table_name', 'PlanAction')])
RealDictRow([('table_schema', 'public'), ('table_name', 'PlanTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Poi')])
RealDictRow([('table_schema', 'public'), ('table_name', 'PoiClassification')])
RealDictRow([('table_schema', 'public'), ('table_name', 'PoiClean')])
RealDictRow([('table_schema', 'public'), ('table_name', 'PoiPoiType')])
RealDictRow([('table_schema', 'public'), ('table_name', 'PoiType')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Profile')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Question')])
RealDictRow([('table_schema', 'public'), ('table_name', 'QuestionTranslate')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Quiz')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Review')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ReviewActions')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ReviewPhoto')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Route')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ScrapingCategory')])
RealDictRow([('table_schema', 'public'), ('table_name', 'ScrapingJob')])
RealDictRow([('table_schema', 'public'), ('table_name', 'Transportation')])
RealDictRow([('table_schema', 'public'), ('table_name', 'TravelType')])
RealDictRow([('table_schema', 'public'), ('table_name', 'User')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserAction')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserDeletionRequest')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserDevice')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserItinerary')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserItineraryGenerationLog')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserItineraryPoi')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserPlan')])
RealDictRow([('table_schema', 'public'), ('table_name', 'UserPreferences')])
RealDictRow([('table_schema', 'public'), ('table_name', 'embedding')])
RealDictRow([('table_schema', 'public'), ('table_name', 'migrations')])
RealDictRow([('table_schema', 'public'), ('table_name', 'spatial_ref_sys')])

In [5]:
# Mở connection
conn = get_db_connection()
cur = conn.cursor()

In [6]:
cur.execute('SELECT * FROM "Poi"')
rows = cur.fetchall()
for poi in rows[:10]:
    print(poi)

RealDictRow([('id', '0f9d2009-9436-46a4-b354-b0261898a39e'), ('created_at', datetime.datetime(2025, 12, 6, 3, 43, 45, 85061)), ('updatedAt', datetime.datetime(2025, 12, 6, 3, 43, 45, 85061)), ('deletedAt', None), ('cityId', '3002ffe3-7c9e-4091-85da-819452858810'), ('source', 'GoogleMaps'), ('content', '{"name":"The Pub Coffee - Beer & Cocktail","placeId":"ChIJ7R9GGLQndTERJRircGTWzn4","description":"","lat":10.8294811,"long":106.7737852,"type":["Cafe","Bar"],"address":"18A17 Tăng Nhơn Phú, Phước Long B, Quận 9, Thành phố Hồ Chí Minh, Vietnam","city":"Ho Chi Minh City","imageUrl":"pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/0d6d8596-ded7-4e10-954b-096aa2783725.jpg","photoUrls":["pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/0d6d8596-ded7-4e10-954b-096aa2783725.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/5f9da691-9b82-4ff2-86ea-7316f6f34028.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/7b15a9c4-8981-4255-be10-bd193951b4e2.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/95c293dc-86be-4fa0-b399-fed54b1f784d.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/aef8efda-45ce-4309-9785-6524c10e4d30.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/cd70d59d-945e-4942-9517-66f2d91dba5a.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/ceb00f6e-9f37-418f-b4a6-92e49c0512a5.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/d4af77fa-1308-4179-b7e9-74a9f17506f3.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/d6249b6a-8c87-4fd3-a078-c9bbdd637880.jpg","pois/images/ChIJ7R9GGLQndTERJRircGTWzn4/e318f6ae-572c-4af4-af87-cde7fd6c5e19.jpg"],"story":""}'), ('raw_data', {'google': {'cid': '9137476420856649765', 'fid': '0x317527b418461fed:0x7eced66470ab1825', 'url': 'https://www.google.com/maps/search/?api=1&query=The%20Pub%20Coffee%20-%20Beer%20%26%20Cocktail&query_place_id=ChIJ7R9GGLQndTERJRircGTWzn4', 'city': 'Ho Chi Minh City', 'menu': None, 'rank': 1, 'kgmid': '/g/11fpkvlhz2', 'phone': '+84 974 188 353', 'price': None, 'state': 'Quận 9, Ho Chi Minh City', 'title': 'The Pub Coffee - Beer & Cocktail', 'emails': [], 'images': None, 'phones': [], 'street': '18A17 Tăng Nhơn Phú', 'address': '18A17 Tăng Nhơn Phú, Phước Long B, Quận 9, Thành phố Hồ Chí Minh, Vietnam', 'orderBy': [], 'placeId': 'ChIJ7R9GGLQndTERJRircGTWzn4', 'reviews': [{'name': 'Thảo Thanh', 'text': 'Quán rộng rãi thoáng mát, giá cả sinh viên', 'stars': 5, 'rating': None, 'reviewId': 'Ci9DQUlRQUNvZENodHljRjlvT21WaFR6QTVTblptZDBWQmRISTVTSFptYm1STmFsRRAB', 'publishAt': 'a week ago', 'reviewUrl': 'https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21WaFR6QTVTblptZDBWQmRISTVTSFptYm1STmFsRRAB!2m1!1s0x0:0x7eced66470ab1825!3m1!1s2@1:CAIQACodChtycF9oOmVhTzA5SnZmd0VBdHI5SHZmbmRNalE%7C0d7_fx6BhHa%7C?hl=en', 'visitedIn': None, 'likesCount': 0, 'reviewerId': '101403667203806476656', 'reviewerUrl': 'https://www.google.com/maps/contrib/101403667203806476656?hl=en', 'isLocalGuide': False, 'reviewOrigin': 'Google', 'reviewContext': {}, 'textTranslated': 'Spacious and airy restaurant, student prices', 'publishedAtDate': '2025-11-23T00:53:17.120Z', 'reviewImageUrls': [], 'originalLanguage': 'vi', 'reviewerPhotoUrl': 'https://lh3.googleusercontent.com/a-/ALV-UjVzeWGK5_Oz2BrxR6WCrbY9bc3mJIXiDYqsbcMI-T3QqaGihcU=s1920-c-rp-mo-br100', 'translatedLanguage': 'en', 'reviewDetailedRating': {'Food': 5, 'Service': 5, 'Atmosphere': 5}, 'responseFromOwnerDate': None, 'responseFromOwnerText': None, 'reviewerNumberOfReviews': 1}, {'name': 'Hieu Pham', 'text': 'Anh nhân viên Trọng Trí quá tuyệt vời', 'stars': 5, 'rating': None, 'reviewId': 'Ci9DQUlRQUNvZENodHljRjlvT2xWRGJtRktXVXMyVWpObmNISlhZVkpaVDNNNGIxRRAB', 'publishAt': '3 weeks ago', 'reviewUrl': 'https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xWRGJtRktXVXMyVWpObmNISlhZVkpaVDNNNGIxRRAB!2m1!1s0x0:0x7eced66470ab1825!3m1!1s2@1:CAIQACodChtycF9oOlVDbmFKWUs2UjNncHJXYVJZT3M4b1E%7C0d3ZEkoVNLU%7C?hl=en', 'visitedIn': None, 'likesCount': 0, 'reviewerId': '112143220850485916789', 'reviewerUrl': 'https://www.google.com/maps/contrib/112143220850485916789?hl=en', 'isLocalGuide': False, 'reviewOrigin': 'Google', 'reviewContext': {}, 'textTranslated': 'Mr. Trong Tri is so wonderful', 'publishedAtDate': '2025-11-10T19:58:40.880Z', 'reviewImageUrls': [], 'originalLanguage': 'vi', 'reviewerPhotoUrl': 'https://lh3.googleusercontent.com/a/ACg8ocI6rvAvZogUUJeUse1iVbUcHT7WoSkI_abokT01Fm2ZQDqvaA=s1920-c-rp-mo-br100', 'translatedLanguage': 'en', 'reviewDetailedRating': {'Food': 5, 'Service': 5, 'Atmosphere': 5}, 'responseFromOwnerDate': '2025-11-22T07:19:37.000Z', 'responseFromOwnerText': 'Phải k đó để biết thưởng nóng cho ẻm', 'reviewerNumberOfReviews': 2}, {'name': 'Oanh Phạm Thị Kiều', 'text': 'quán view thoáng, nhiệt tình, đồ uống siêu ngon ạ', 'stars': 5, 'rating': None, 'reviewId': 'Ci9DQUlRQUNvZENodHljRjlvT2pWVGFsUlpORVpPVjBjd1JGcHFWRzVoWDJocGJYYxAB', 'publishAt': 'a month ago', 'reviewUrl': 'https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2pWVGFsUlpORVpPVjBjd1JGcHFWRzVoWDJocGJYYxAB!2m1!1s0x0:0x7eced66470ab1825!3m1!1s2@1:CAIQACodChtycF9oOjVTalRZNEZOV0cwRFpqVG5hX2hpbXc%7C0d0L337MKzu%7C?hl=en', 'visitedIn': None, 'likesCount': 0, 'reviewerId': '110275962475137145795', 'reviewerUrl': 'https://www.google.com/maps/contrib/110275962475137145795?hl=en', 'isLocalGuide': False, 'reviewOrigin': 'Google', 'reviewContext': {'Group size': 'Suitable for all group sizes'}, 'textTranslated': 'The shop has a great view, friendly staff, and delicious drinks.', 'publishedAtDate': '2025-11-01T01:23:16.140Z', 'reviewImageUrls': [], 'originalLanguage': 'vi', 'reviewerPhotoUrl': 'https://lh3.googleusercontent.com/a/ACg8ocLQWY4nD9u2fbL_I65qpCwfGNRzIXKvmTv5bL2cLWNwaBdqBw=s1920-c-rp-mo-br100', 'translatedLanguage': 'en', 'reviewDetailedRating': {}, 'responseFromOwnerDate': '2025-11-22T07:19:06.000Z', 'responseFromOwnerText': 'Trái tim', 'reviewerNumberOfReviews': 2}], 'tiktoks': [], 'website': None, 'discords': [], 'hotelAds': [], 'imageUrl': 'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwlrYb68I8vRz1MIT8NEv_cCZidFtKMqJ_xB8G6jiYDrgU1EREBbOFiNYM4_Y05EVMzZXRR_0SRam-x93cwTPhtLS3lU_gwRIV-Zm6xrNeAXKCFxaYCvwJ3LPk3QONPdVJ0-zev=w408-h544-k-no', 'language': 'en', 'location': {'lat': 10.8294811, 'lng': 106.7737852}, 'plusCode': 'RQHF+QG Thủ Đức City, Ho Chi Minh City, Vietnam', 'subTitle': None, 'twitters': [], 'youtubes': [], 'facebooks': [], 'gasPrices': [], 'imageUrls': ['https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwlrYb68I8vRz1MIT8NEv_cCZidFtKMqJ_xB8G6jiYDrgU1EREBbOFiNYM4_Y05EVMzZXRR_0SRam-x93cwTPhtLS3lU_gwRIV-Zm6xrNeAXKCFxaYCvwJ3LPk3QONPdVJ0-zev=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipNl1ba0rtKO17wm_8_eyko_nPJnHu0aieMni07w=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipMahGH6wS4tt8l-p8Yf4ctUVAA2cc5ibp1YpY00=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipOqjUr0DosL1PfpAl4qsXnhZpmttzBtMX1nveM_=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz8EQWZDqU5ua6GLl33qkUB62NXKyLwx8yfFs6hbrHwnvg4js--Snu95_8c2lPhfinVQJRYMtpBvx8ZbWrjmc-Uzk4Zhp4Gv6zKTnwh9TwEexoK0-03qKyWC9GIb9x4dVu-PEsVuw=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyw6fqGYYHgt4xBgOoOvNT6AVehhlKTy3rXQwQHbOCpSYrM2h1bVxl_TgDjyhmjGYIJY_fkA58HnkE1MD36OqpLR5so_xTsiKULN81IwVvCKZh0PPBArKl_-De3PP_qLwaPU7Zk=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipMY2EOVvNFixS5sIfqIpNqU8wlPccUJZR8_hGO1=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipOS5w7PWsZNheE364HleK0_EMLtNLTJytfX0NTN=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipM97WK1fYF1jXcN0e4UMbMNJlB4OSBxGDEIQCyi=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipOB61ysyrxH5izxZ5AEXKngWKtXTcq7qvkIWR3e=w1920-h1080-k-no'], 'linkedIns': [], 'locatedIn': None, 'scrapedAt': '2025-12-05T04:26:35.491Z', 'categories': ['Cafe', 'Bar'], 'hotelStars': None, 'instagrams': [], 'pinterests': [], 'placesTags': [], 'postalCode': None, 'totalScore': 4.9, 'webResults': [], 'checkInDate': None, 'countryCode': 'VN', 'description': None, 'imagesCount': 55, 'reviewsTags': [], 'bookingLinks': [], 'categoryName': 'Cafe', 'checkOutDate': None, 'inputPlaceId': None, 'neighborhood': 'Phước Long B, Quận 9', 'openingHours': [{'day': 'Monday', 'hours': 'Open 24 hours'}, {'day': 'Tuesday', 'hours': 'Open 24 hours'}, {'day': 'Wednesday', 'hours': 'Open 24 hours'}, {'day': 'Thursday', 'hours': 'Open 24 hours'}, {'day': 'Friday', 'hours': 'Open 24 hours'}, {'day': 'Saturday', 'hours': 'Open 24 hours'}, {'day': 'Sunday', 'hours': 'Open 24 hours'}], 'ownerUpdates': [], 'reviewsCount': 181, 'searchString': 'pub', 'googleFoodUrl': None, 'searchPageUrl': 'https://www.google.com/maps/search/pub/@10.859038390216558,106.75577809191171,13z?hl=en', 'userPlaceNote': None, 'additionalInfo': {'Crowd': [{'Groups': True}], 'Payments': [{'NFC mobile payments': True}], 'Planning': [{'Accepts reservations': True}], 'Amenities': [{'Bar onsite': True}, {'Restroom': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Coffee': True}, {'Hard liquor': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}], 'Highlights': [{'Great beer selection': True}, {'Great coffee': True}, {'Live music': True}, {'Live performances': True}], 'Dining options': [{'Table service': True}], 'Service options': [{'No-contact delivery': True}, {'Delivery': True}, {'Drive-through': True}, {'Takeout': True}, {'Dine-in': True}]}, 'restaurantData': {'tableReservationProvider': None}, 'imageCategories': ['All', 'Menu', 'Videos', 'Food & drink', 'By owner', 'Street View & 360°'], 'isAdvertisement': False, 'leadsEnrichment': [], 'phonesUncertain': [], 'reserveTableUrl': None, 'hotelDescription': None, 'peopleAlsoSearch': [{'title': '39 𝐁𝐄𝐄𝐑 FOOD', 'category': 'People also search for', 'totalScore': 3.8, 'reviewsCount': 63}, {'title': 'Quán Bar', 'category': 'People also search for', 'totalScore': 5, 'reviewsCount': 3}, {'title': '99 Coffee Lounge', 'category': 'People also search for', 'totalScore': 4.5, 'reviewsCount': 10}, {'title': 'Mini Pod Cocktail Bar', 'category': 'People also search for', 'totalScore': 5, 'reviewsCount': 20}, {'title': 'Chill Beer 97', 'category': 'People also search for', 'totalScore': 3, 'reviewsCount': 1}], 'phoneUnformatted': '+84974188353', 'claimThisBusiness': False, 'permanentlyClosed': False, 'temporarilyClosed': False, 'hotelReviewSummary': None, 'questionsAndAnswers': [], 'reviewsDistribution': {'oneStar': 4, 'twoStar': 0, 'fiveStar': 175, 'fourStar': 2, 'threeStar': 0}, 'similarHotelsNearby': None, 'popularTimesLiveText': 'Now: Usually not too busy', 'updatesFromCustomers': None, 'popularTimesHistogram': {'Fr': [{'hour': 4, 'occupancyPercent': 81}, {'hour': 5, 'occupancyPercent': 75}, {'hour': 6, 'occupancyPercent': 68}, {'hour': 7, 'occupancyPercent': 62}, {'hour': 8, 'occupancyPercent': 50}, {'hour': 9, 'occupancyPercent': 37}, {'hour': 10, 'occupancyPercent': 37}, {'hour': 11, 'occupancyPercent': 25}, {'hour': 12, 'occupancyPercent': 43}, {'hour': 13, 'occupancyPercent': 62}, {'hour': 14, 'occupancyPercent': 62}, {'hour': 15, 'occupancyPercent': 56}, {'hour': 16, 'occupancyPercent': 50}, {'hour': 17, 'occupancyPercent': 31}, {'hour': 18, 'occupancyPercent': 18}, {'hour': 19, 'occupancyPercent': 18}, {'hour': 20, 'occupancyPercent': 37}, {'hour': 21, 'occupancyPercent': 43}, {'hour': 22, 'occupancyPercent': 68}, {'hour': 23, 'occupancyPercent': 75}, {'hour': 0, 'occupancyPercent': 68}, {'hour': 1, 'occupancyPercent': 50}, {'hour': 2, 'occupancyPercent': 43}, {'hour': 3, 'occupancyPercent': 50}], 'Mo': [{'hour': 4, 'occupancyPercent': 25}, {'hour': 5, 'occupancyPercent': 25}, {'hour': 6, 'occupancyPercent': 18}, {'hour': 7, 'occupancyPercent': 12}, {'hour': 8, 'occupancyPercent': 18}, {'hour': 9, 'occupancyPercent': 12}, {'hour': 10, 'occupancyPercent': 31}, {'hour': 11, 'occupancyPercent': 37}, {'hour': 12, 'occupancyPercent': 50}, {'hour': 13, 'occupancyPercent': 50}, {'hour': 14, 'occupancyPercent': 87}, {'hour': 15, 'occupancyPercent': 50}, {'hour': 16, 'occupancyPercent': 50}, {'hour': 17, 'occupancyPercent': 43}, {'hour': 18, 'occupancyPercent': 37}, {'hour': 19, 'occupancyPercent': 56}, {'hour': 20, 'occupancyPercent': 37}, {'hour': 21, 'occupancyPercent': 43}, {'hour': 22, 'occupancyPercent': 37}, {'hour': 23, 'occupancyPercent': 56}, {'hour': 0, 'occupancyPercent': 50}, {'hour': 1, 'occupancyPercent': 31}, {'hour': 2, 'occupancyPercent': 18}, {'hour': 3, 'occupancyPercent': 25}], 'Sa': [{'hour': 4, 'occupancyPercent': 37}, {'hour': 5, 'occupancyPercent': 56}, {'hour': 6, 'occupancyPercent': 68}, {'hour': 7, 'occupancyPercent': 93}, {'hour': 8, 'occupancyPercent': 81}, {'hour': 9, 'occupancyPercent': 75}, {'hour': 10, 'occupancyPercent': 81}, {'hour': 11, 'occupancyPercent': 43}, {'hour': 12, 'occupancyPercent': 56}, {'hour': 13, 'occupancyPercent': 50}, {'hour': 14, 'occupancyPercent': 75}, {'hour': 15, 'occupancyPercent': 50}, {'hour': 16, 'occupancyPercent': 37}, {'hour': 17, 'occupancyPercent': 25}, {'hour': 18, 'occupancyPercent': 31}, {'hour': 19, 'occupancyPercent': 43}, {'hour': 20, 'occupancyPercent': 62}, {'hour': 21, 'occupancyPercent': 81}, {'hour': 22, 'occupancyPercent': 75}, {'hour': 23, 'occupancyPercent': 68}, {'hour': 0, 'occupancyPercent': 50}, {'hour': 1, 'occupancyPercent': 37}, {'hour': 2, 'occupancyPercent': 31}, {'hour': 3, 'occupancyPercent': 43}], 'Su': [{'hour': 4, 'occupancyPercent': 31}, {'hour': 5, 'occupancyPercent': 50}, {'hour': 6, 'occupancyPercent': 68}, {'hour': 7, 'occupancyPercent': 62}, {'hour': 8, 'occupancyPercent': 43}, {'hour': 9, 'occupancyPercent': 18}, {'hour': 10, 'occupancyPercent': 6}, {'hour': 11, 'occupancyPercent': 0}, {'hour': 12, 'occupancyPercent': 12}, {'hour': 13, 'occupancyPercent': 25}, {'hour': 14, 'occupancyPercent': 43}, {'hour': 15, 'occupancyPercent': 56}, {'hour': 16, 'occupancyPercent': 43}, {'hour': 17, 'occupancyPercent': 50}, {'hour': 18, 'occupancyPercent': 43}, {'hour': 19, 'occupancyPercent': 56}, {'hour': 20, 'occupancyPercent': 75}, {'hour': 21, 'occupancyPercent': 87}, {'hour': 22, 'occupancyPercent': 68}, {'hour': 23, 'occupancyPercent': 56}, {'hour': 0, 'occupancyPercent': 62}, {'hour': 1, 'occupancyPercent': 75}, {'hour': 2, 'occupancyPercent': 62}, {'hour': 3, 'occupancyPercent': 50}], 'Th': [{'hour': 4, 'occupancyPercent': 43}, {'hour': 5, 'occupancyPercent': 37}, {'hour': 6, 'occupancyPercent': 37}, {'hour': 7, 'occupancyPercent': 31}, {'hour': 8, 'occupancyPercent': 25}, {'hour': 9, 'occupancyPercent': 25}, {'hour': 10, 'occupancyPercent': 31}, {'hour': 11, 'occupancyPercent': 43}, {'hour': 12, 'occupancyPercent': 50}, {'hour': 13, 'occupancyPercent': 31}, {'hour': 14, 'occupancyPercent': 18}, {'hour': 15, 'occupancyPercent': 6}, {'hour': 16, 'occupancyPercent': 6}, {'hour': 17, 'occupancyPercent': 25}, {'hour': 18, 'occupancyPercent': 43}, {'hour': 19, 'occupancyPercent': 50}, {'hour': 20, 'occupancyPercent': 56}, {'hour': 21, 'occupancyPercent': 43}, {'hour': 22, 'occupancyPercent': 31}, {'hour': 23, 'occupancyPercent': 43}, {'hour': 0, 'occupancyPercent': 37}, {'hour': 1, 'occupancyPercent': 31}, {'hour': 2, 'occupancyPercent': 25}, {'hour': 3, 'occupancyPercent': 37}], 'Tu': [{'hour': 4, 'occupancyPercent': 37}, {'hour': 5, 'occupancyPercent': 37}, {'hour': 6, 'occupancyPercent': 31}, {'hour': 7, 'occupancyPercent': 31}, {'hour': 8, 'occupancyPercent': 12}, {'hour': 9, 'occupancyPercent': 12}, {'hour': 10, 'occupancyPercent': 12}, {'hour': 11, 'occupancyPercent': 18}, {'hour': 12, 'occupancyPercent': 43}, {'hour': 13, 'occupancyPercent': 56}, {'hour': 14, 'occupancyPercent': 62}, {'hour': 15, 'occupancyPercent': 37}, {'hour': 16, 'occupancyPercent': 31}, {'hour': 17, 'occupancyPercent': 25}, {'hour': 18, 'occupancyPercent': 18}, {'hour': 19, 'occupancyPercent': 31}, {'hour': 20, 'occupancyPercent': 37}, {'hour': 21, 'occupancyPercent': 37}, {'hour': 22, 'occupancyPercent': 43}, {'hour': 23, 'occupancyPercent': 43}, {'hour': 0, 'occupancyPercent': 62}, {'hour': 1, 'occupancyPercent': 50}, {'hour': 2, 'occupancyPercent': 37}, {'hour': 3, 'occupancyPercent': 25}], 'We': [{'hour': 4, 'occupancyPercent': 43}, {'hour': 5, 'occupancyPercent': 18}, {'hour': 6, 'occupancyPercent': 12}, {'hour': 7, 'occupancyPercent': 25}, {'hour': 8, 'occupancyPercent': 56}, {'hour': 9, 'occupancyPercent': 87}, {'hour': 10, 'occupancyPercent': 100}, {'hour': 11, 'occupancyPercent': 87}, {'hour': 12, 'occupancyPercent': 75}, {'hour': 13, 'occupancyPercent': 56}, {'hour': 14, 'occupancyPercent': 50}, {'hour': 15, 'occupancyPercent': 43}, {'hour': 16, 'occupancyPercent': 31}, {'hour': 17, 'occupancyPercent': 18}, {'hour': 18, 'occupancyPercent': 18}, {'hour': 19, 'occupancyPercent': 37}, {'hour': 20, 'occupancyPercent': 75}, {'hour': 21, 'occupancyPercent': 56}, {'hour': 22, 'occupancyPercent': 37}, {'hour': 23, 'occupancyPercent': 12}, {'hour': 0, 'occupancyPercent': 6}, {'hour': 1, 'occupancyPercent': 18}, {'hour': 2, 'occupancyPercent': 31}, {'hour': 3, 'occupancyPercent': 37}]}, 'tableReservationLinks': [], 'additionalOpeningHours': None, 'popularTimesLivePercent': None, 'openingHoursBusinessConfirmationText': None}, 'social': {'tiktok': [], 'youtube': [], 'instagram': []}}), ('metadata', {'city': 'Ho Chi Minh City', 'poiType': ['Cafe', 'Bar'], 'totalScore': 4.9, 'imagesCount': 55, 'openingHours': [{'day': 'Monday', 'hours': 'Open 24 hours'}, {'day': 'Tuesday', 'hours': 'Open 24 hours'}, {'day': 'Wednesday', 'hours': 'Open 24 hours'}, {'day': 'Thursday', 'hours': 'Open 24 hours'}, {'day': 'Friday', 'hours': 'Open 24 hours'}, {'day': 'Saturday', 'hours': 'Open 24 hours'}, {'day': 'Sunday', 'hours': 'Open 24 hours'}], 'reviewsCount': 181, 'additionalInfo': {'Crowd': [{'Groups': True}], 'Payments': [{'NFC mobile payments': True}], 'Planning': [{'Accepts reservations': True}], 'Amenities': [{'Bar onsite': True}, {'Restroom': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Coffee': True}, {'Hard liquor': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}], 'Highlights': [{'Great beer selection': True}, {'Great coffee': True}, {'Live music': True}, {'Live performances': True}], 'Dining options': [{'Table service': True}], 'Service options': [{'No-contact delivery': True}, {'Delivery': True}, {'Drive-through': True}, {'Takeout': True}, {'Dine-in': True}]}}), ('placeId', 'ChIJ7R9GGLQndTERJRircGTWzn4'), ('audioUrl', None), ('location', '0101000020E61000003F085CB285B15A40DB4C2ABFB1A82540')])

# Các feature cần phải lấy ra từ table Poi

In [40]:
# id UUID PRIMARY KEY, lấy từ cột id
# name TEXT NOT NULL, lấy từ cột content
# address TEXT, lấy từ cột content 
# lat DOUBLE PRECISION NOT NULL, lấy từ cột content
# lon DOUBLE PRECISION NOT NULL, lấy từ cột content 
# geom GEOMETRY(Point, 4326) NOT NULL, tạo ra code
# poi_type TEXT, lấy từ cột content 
# stay_time DOUBLE PRECISION CHECK (stay_time >= 0), default 30
# avg_stars DOUBLE PRECISION CHECK (avg_stars BETWEEN 0 AND 5), lấy từ cột raw_data
# total_reviews INTEGER CHECK (total_reviews >= 0), từ cột raw_data
# normalize_stars_reviews DOUBLE PRECISION # normalize avg_stars và total_reviews về thang điểm 0-1

# Tạo 1 file csv

In [ ]:
file_path = os.path.join(os.getcwd(), "data/data.csv")
print(f"File path: {file_path}")

# Tạo thư mục nếu chưa tồn tại
os.makedirs(os.path.dirname(file_path), exist_ok=True)

# Tạo file nếu chưa tồn tại
if not os.path.exists(file_path):
    with open(file_path, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)

# Đọc dữ liệu
if not os.path.exists(file_path) or os.stat(file_path).st_size == 0:
    df = pd.DataFrame()   # df rỗng, chưa có cột
else:
    df = pd.read_csv(file_path)

print(df)

File path: c:\Users\nguye\Desktop\vinamo\Kyanon-support-localtion\scripts\clean_data\data/data1.csv
Empty DataFrame
Columns: []
Index: []

# Trích xuất các trường

In [10]:
# id
id = []
cur.execute('SELECT id FROM "Poi"')
rows = cur.fetchall()
for poi in rows:
    id.append(poi['id'])
df["id"] = id

In [ ]:
import json

name = []
address = []
lat = []
lon = []
poi_type = []

cur.execute('SELECT content FROM "Poi"')
rows = cur.fetchall()

for poi in rows:
    raw = poi.get("content")

    if not isinstance(raw, str):
        continue

    try:
        content = json.loads(raw)  # prase_json
    except Exception as e:
        print("Invalid JSON:", raw)
        continue

    name.append(content.get("name"))
    address.append(content.get("address"))
    lat.append(content.get("lat"))
    lon.append(content.get("long"))
    types = content.get("type")
    if isinstance(types, list):
        poi_type.append(",".join(types))
    else:
        poi_type.append(types)

df["name"] = name
df["address"] = address
df["lat"] = lat
df["lon"] = lon
df["poi_type"] = poi_type

Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=
Raw content type: <class 'str'>
end=

In [44]:
# avg_stars và total_reviews từ raw_data
avg_stars = []
total_reviews = []
cur.execute('SELECT raw_data FROM "Poi"')
rows = cur.fetchall()
for poi in rows:
    raw_data = poi.get("raw_data")
    google = raw_data.get("google")
    avg_stars.append(google.get("totalScore"))
    total_reviews.append(google.get("reviewsCount"))
df["avg_stars"] = avg_stars
df["total_reviews"] = total_reviews

# Xuất vào csv

In [45]:
# Kiểm tra dữ liệu hiện tại của avg_stars và total_reviews
print("Kiểm tra dữ liệu avg_stars và total_reviews:")
print(f"Kiểu dữ liệu avg_stars: {df['avg_stars'].dtype}")
print(f"Kiểu dữ liệu total_reviews: {df['total_reviews'].dtype}")
print(f"Số lượng giá trị null trong avg_stars: {df['avg_stars'].isna().sum()}")
print(f"Số lượng giá trị null trong total_reviews: {df['total_reviews'].isna().sum()}")
print(f"\nMẫu dữ liệu:")
print(df[['name', 'avg_stars', 'total_reviews']].head(15))
print(f"\nCác giá trị unique của avg_stars: {df['avg_stars'].unique()[:20]}")
print(f"\nCác giá trị unique của total_reviews: {df['total_reviews'].unique()[:20]}")

Kiểm tra dữ liệu avg_stars và total_reviews:
Kiểu dữ liệu avg_stars: object
Kiểu dữ liệu total_reviews: object
Số lượng giá trị null trong avg_stars: 2
Số lượng giá trị null trong total_reviews: 0

Mẫu dữ liệu:
                                                 name avg_stars total_reviews
0                    The Pub Coffee - Beer & Cocktail       4.9           181
1                                             Julieta       4.3          2053
2                  BAIETA Restaurant Saigon Thao Dien       4.5           285
3                           Parroquia San Felipe Neri       4.7           329
4                                              BÀ BAR       4.8           182
5                                    Art Bar Viet Nam       4.9           165
6   Ngỡ Cafe | Cà phê view đẹp Thủ Đức | Coffee ng...       4.7           216
7                              TEEMAY COFFEE ROASTERS         5           275
8                        La Mafia se sienta a la mesa       4.3          1322
9                                          Bar tocata         4          1321
10                           BiaCraft Xuan Thuy | D.2       4.6          1624
11                         K-CITY (Korean Cafe & Bar)       4.7            15
12                                       Canalis Club       4.4          1637
13                 LOGAN STATION - The Gentlemen Café       4.6           352
14                                     Gét Gô Rooftop       4.7           166

Các giá trị unique của avg_stars: [4.9 4.3 4.5 4.7 4.8 5 4 4.6 4.4 4.1 4.2 '5' 3.9 3.5 3.6 3.8 None 3.4 3.7
 3.1]

Các giá trị unique của total_reviews: [181 2053 285 329 182 165 216 275 1322 1321 1624 15 1637 352 166 1450 1393
 2161 8 83]

In [46]:
# Xử lý avg_stars và total_reviews theo yêu cầu
# Nếu avg_stars hoặc total_reviews không có giá trị hoặc 1 trong 2 có giá trị 0
# thì cả 2 trường sẽ được đưa về giá trị thấp nhất

# Chuyển đổi sang numeric, các giá trị không hợp lệ sẽ thành NaN
df['avg_stars'] = pd.to_numeric(df['avg_stars'], errors='coerce')
df['total_reviews'] = pd.to_numeric(df['total_reviews'], errors='coerce')

# Tìm giá trị thấp nhất của mỗi cột (không tính null và 0)
min_avg_stars = df[(df['avg_stars'].notna()) & (df['avg_stars'] > 0)]['avg_stars'].min()
min_total_reviews = df[(df['total_reviews'].notna()) & (df['total_reviews'] > 0)]['total_reviews'].min()

print(f"Giá trị thấp nhất của avg_stars (không tính null và 0): {min_avg_stars}")
print(f"Giá trị thấp nhất của total_reviews (không tính null và 0): {min_total_reviews}")

# Tạo mask để xác định các hàng cần cập nhật
# Điều kiện: avg_stars hoặc total_reviews là null, hoặc 1 trong 2 bằng 0
mask = (
    df['avg_stars'].isna() | 
    df['total_reviews'].isna() | 
    (df['avg_stars'] == 0) | 
    (df['total_reviews'] == 0)
)

print(f"\nSố lượng hàng cần cập nhật: {mask.sum()}")
print(f"Trước khi cập nhật:")
print(df[mask][['name', 'avg_stars', 'total_reviews']].head(15))

# Cập nhật cả 2 cột về giá trị thấp nhất
df.loc[mask, 'avg_stars'] = min_avg_stars
df.loc[mask, 'total_reviews'] = min_total_reviews

print(f"\nSau khi cập nhật:")
print(df[mask][['name', 'avg_stars', 'total_reviews']].head(15))

print(f"\nKiểm tra lại:")
print(f"Số lượng giá trị null trong avg_stars: {df['avg_stars'].isna().sum()}")
print(f"Số lượng giá trị null trong total_reviews: {df['total_reviews'].isna().sum()}")
print(f"Số lượng giá trị 0 trong avg_stars: {(df['avg_stars'] == 0).sum()}")
print(f"Số lượng giá trị 0 trong total_reviews: {(df['total_reviews'] == 0).sum()}")

Giá trị thấp nhất của avg_stars (không tính null và 0): 3.0
Giá trị thấp nhất của total_reviews (không tính null và 0): 1

Số lượng hàng cần cập nhật: 10
Trước khi cập nhật:
                                                   name  avg_stars  \
255                                Co.opmart Chu Van An        4.1
257                        PICKLEBALL COLEGIO LA COLINA        NaN
308                         GOPICK - 250 Lương Định Của        4.6
597                            Tân Định Catholic Church        4.4
681                      Nhim Sau Rieng Gelato & Coffee        4.8
716                             Café Slow in the Garden        4.8
746                                        Chợ Hạt Điều        4.2
827                                        Ăn Vặt Bé Bơ        5.0
877   BIA HƠI HÀ NỘI ĐẠI VIỆT | QUÁN BIA HƠI QUẬN 12...        3.8
1452                                    parque infantil        NaN

      total_reviews
255               0
257               0
308               0
597               0
681               0
716               0
746               0
827               0
877               0
1452              0

Sau khi cập nhật:
                                                   name  avg_stars  \
255                                Co.opmart Chu Van An        3.0
257                        PICKLEBALL COLEGIO LA COLINA        3.0
308                         GOPICK - 250 Lương Định Của        3.0
597                            Tân Định Catholic Church        3.0
681                      Nhim Sau Rieng Gelato & Coffee        3.0
716                             Café Slow in the Garden        3.0
746                                        Chợ Hạt Điều        3.0
827                                        Ăn Vặt Bé Bơ        3.0
877   BIA HƠI HÀ NỘI ĐẠI VIỆT | QUÁN BIA HƠI QUẬN 12...        3.0
1452                                    parque infantil        3.0

      total_reviews
255               1
257               1
308               1
597               1
681               1
716               1
746               1
827               1
877               1
1452              1

Kiểm tra lại:
Số lượng giá trị null trong avg_stars: 0
Số lượng giá trị null trong total_reviews: 0
Số lượng giá trị 0 trong avg_stars: 0
Số lượng giá trị 0 trong total_reviews: 0

In [47]:
df.to_csv(file_path, index=False)

# Thêm các feature

In [ ]:
# Crowd,Children,Offerings,Atmosphere,Highlights,Popular for,Dining options, Accessibility options lấy từ metadata.additionalInfo

In [8]:
cur.execute('SELECT metadata FROM "Poi"')
rows = cur.fetchall()
for poi in rows[:10]:
    print(poi)

RealDictRow([('metadata', {'city': 'Ho Chi Minh City', 'poiType': ['Cafe', 'Bar'], 'totalScore': 4.9, 'imagesCount': 55, 'openingHours': [{'day': 'Monday', 'hours': 'Open 24 hours'}, {'day': 'Tuesday', 'hours': 'Open 24 hours'}, {'day': 'Wednesday', 'hours': 'Open 24 hours'}, {'day': 'Thursday', 'hours': 'Open 24 hours'}, {'day': 'Friday', 'hours': 'Open 24 hours'}, {'day': 'Saturday', 'hours': 'Open 24 hours'}, {'day': 'Sunday', 'hours': 'Open 24 hours'}], 'reviewsCount': 181, 'additionalInfo': {'Crowd': [{'Groups': True}], 'Payments': [{'NFC mobile payments': True}], 'Planning': [{'Accepts reservations': True}], 'Amenities': [{'Bar onsite': True}, {'Restroom': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Coffee': True}, {'Hard liquor': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}], 'Highlights': [{'Great beer selection': True}, {'Great coffee': True}, {'Live music': True}, {'Live performances': True}], 'Dining options': [{'Table service': True}], 'Service options': [{'No-contact delivery': True}, {'Delivery': True}, {'Drive-through': True}, {'Takeout': True}, {'Dine-in': True}]}})])
RealDictRow([('metadata', {'city': 'Málaga', 'poiType': ['Cafe'], 'additionalInfo': {'Crowd': [{'College students': True}, {'Groups': True}, {'Tourists': True}], 'Parking': [{'Paid parking lot': True}, {'Paid street parking': True}, {'Usually difficult to find a space': True}], 'Children': [{'Good for kids': True}], 'Payments': [{'Credit cards': True}, {'Debit cards': True}, {'NFC mobile payments': True}, {'Credit cards': True}], 'Amenities': [{'Restroom': True}, {'Wi-Fi': True}, {'Free Wi-Fi': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Coffee': True}, {'Healthy options': True}, {'Organic dishes': True}, {'Prepared foods': True}, {'Quick bite': True}, {'Vegan options': True}, {'Vegetarian options': True}, {'Wine': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}, {'Trendy': True}], 'Highlights': [{'Great coffee': True}, {'Great dessert': True}, {'Great tea selection': True}], 'Popular for': [{'Breakfast': True}, {'Good for working on laptop': True}], 'Accessibility': [{'Wheelchair accessible entrance': True}, {'Wheelchair accessible restroom': True}, {'Wheelchair accessible seating': True}, {'Wheelchair accessible parking lot': False}], 'Dining options': [{'Breakfast': True}, {'Brunch': True}, {'Lunch': True}, {'Dessert': True}, {'Seating': True}, {'Table service': True}], 'Service options': [{'Outdoor seating': True}, {'Delivery': True}, {'Onsite services': True}, {'Takeout': True}, {'Dine-in': True}]}})])
RealDictRow([('metadata', {'city': 'Ho Chi Minh City', 'poiType': ['Restaurant', 'Bar', 'Cocktail bar', 'Coffee shop', 'Family restaurant', 'Mediterranean restaurant'], 'totalScore': 4.5, 'imagesCount': 724, 'openingHours': [{'day': 'Monday', 'hours': 'Closed'}, {'day': 'Tuesday', 'hours': '11\u202fAM to 12\u202fAM'}, {'day': 'Wednesday', 'hours': '11\u202fAM to 12\u202fAM'}, {'day': 'Thursday', 'hours': '11\u202fAM to 12\u202fAM'}, {'day': 'Friday', 'hours': '11\u202fAM to 12\u202fAM'}, {'day': 'Saturday', 'hours': '11:30\u202fAM to 12\u202fAM'}, {'day': 'Sunday', 'hours': '11:30\u202fAM to 12\u202fAM'}], 'reviewsCount': 285, 'additionalInfo': {'Pets': [{'Dogs allowed': True}], 'Crowd': [{'Family-friendly': True}, {'Groups': True}, {'LGBTQ+ friendly': True}, {'Tourists': True}], 'Parking': [{'Free parking lot': True}, {'Free street parking': True}, {'Usually plenty of parking': True}], 'Children': [{'Good for kids': True}], 'Payments': [{'Credit cards': True}, {'Debit cards': True}], 'Planning': [{'Dinner reservations recommended': True}, {'Accepts reservations': True}], 'Amenities': [{'Bar onsite': True}, {'Restroom': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Coffee': True}, {'Happy hour drinks': True}, {'Hard liquor': True}, {'Small plates': True}, {'Vegetarian options': True}, {'Wine': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}, {'Romantic': True}], 'Highlights': [{'Great beer selection': True}, {'Great cocktails': True}, {'Great coffee': True}, {'Great dessert': True}, {'Great wine list': True}, {'Rooftop seating': True}], 'Popular for': [{'Lunch': True}, {'Dinner': True}, {'Solo dining': True}], 'Accessibility': [{'Wheelchair accessible seating': True}], 'Dining options': [{'Brunch': True}, {'Lunch': True}, {'Dinner': True}, {'Catering': True}, {'Counter service': True}, {'Dessert': True}, {'Seating': True}, {'Table service': True}], 'Service options': [{'Outdoor seating': True}, {'Takeout': True}, {'Dine-in': True}]}})])
RealDictRow([('metadata', {'city': 'Málaga', 'poiType': ['Catholic church', 'Tourist attraction'], 'additionalInfo': {'Accessibility': [{'Wheelchair accessible entrance': True}]}})])
RealDictRow([('metadata', {'city': 'Ho Chi Minh City', 'poiType': ['Cocktail bar', 'Cafe'], 'totalScore': 4.8, 'imagesCount': 302, 'openingHours': [{'day': 'Monday', 'hours': '10\u202fAM to 12\u202fAM'}, {'day': 'Tuesday', 'hours': '10\u202fAM to 12\u202fAM'}, {'day': 'Wednesday', 'hours': '10\u202fAM to 12\u202fAM'}, {'day': 'Thursday', 'hours': '10\u202fAM to 12\u202fAM'}, {'day': 'Friday', 'hours': '10\u202fAM to 12\u202fAM'}, {'day': 'Saturday', 'hours': '8\u202fAM to 12\u202fAM'}, {'day': 'Sunday', 'hours': '8\u202fAM to 12\u202fAM'}], 'reviewsCount': 182, 'additionalInfo': {'Pets': [{'Dogs allowed': True}], 'Crowd': [{'Groups': True}, {'LGBTQ+ friendly': True}, {'Transgender safespace': True}], 'Parking': [{'Valet parking': True}], 'Payments': [{'Credit cards': True}, {'Debit cards': True}, {'NFC mobile payments': True}], 'Planning': [{'Accepts reservations': True}], 'Amenities': [{'Gender-neutral restroom': True}, {'Restroom': True}, {'Wi-Fi': True}, {'Free Wi-Fi': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Food': True}, {'Happy hour drinks': True}, {'Happy hour food': True}, {'Hard liquor': True}, {'Wine': True}], 'Atmosphere': [{'Casual': True}], 'Highlights': [{'Live music': True}, {'Live performances': True}], 'Dining options': [{'Seating': True}, {'Table service': True}], 'Service options': [{'Outdoor seating': True}, {'No-contact delivery': True}, {'Delivery': True}, {'Drive-through': True}, {'Onsite services': True}, {'Takeout': True}, {'Dine-in': True}], 'From the business': [{'Identifies as women-owned': True}]}})])
RealDictRow([('metadata', {'city': 'Ho Chi Minh City', 'poiType': ['Bar', 'Art gallery', 'Cocktail bar'], 'totalScore': 4.9, 'imagesCount': 58, 'openingHours': [{'day': 'Monday', 'hours': '4\u202fPM to 12\u202fAM'}, {'day': 'Tuesday', 'hours': '4\u202fPM to 12\u202fAM'}, {'day': 'Wednesday', 'hours': '4\u202fPM to 12\u202fAM'}, {'day': 'Thursday', 'hours': '4\u202fPM to 12\u202fAM'}, {'day': 'Friday', 'hours': '4\u202fPM to 12\u202fAM'}, {'day': 'Saturday', 'hours': '4\u202fPM to 12\u202fAM'}, {'day': 'Sunday', 'hours': '4\u202fPM to 12\u202fAM'}], 'reviewsCount': 165, 'additionalInfo': {'Pets': [{'Dogs allowed': True}], 'Crowd': [{'Groups': True}, {'LGBTQ+ friendly': True}, {'Tourists': True}, {'Transgender safespace': True}], 'Parking': [{'Free parking lot': True}, {'Free street parking': True}, {'Valet parking': True}], 'Payments': [{'Credit cards': True}, {'Debit cards': True}, {'Credit cards': True}], 'Planning': [{'Accepts reservations': True}], 'Amenities': [{'Restroom': True}, {'Wi-Fi': True}, {'Free Wi-Fi': True}], 'Offerings': [{'Alcohol': True}, {'Cocktails': True}, {'Food': True}, {'Food at bar': True}, {'Hard liquor': True}, {'Wine': True}], 'Atmosphere': [{'Cozy': True}], 'Highlights': [{'Bar games': True}, {'Great cocktails': True}, {'Live performances': True}], 'Accessibility': [{'Wheelchair accessible entrance': True}, {'Wheelchair accessible parking lot': True}, {'Wheelchair accessible seating': True}, {'Assistive hearing loop': False}], 'Dining options': [{'Seating': True}, {'Table service': True}], 'Service options': [{'Takeout': True}, {'Dine-in': True}, {'Delivery': False}]}})])
RealDictRow([('metadata', {'city': 'Ho Chi Minh City', 'poiType': ['Coffee shop'], 'totalScore': 4.7, 'imagesCount': 801, 'openingHours': [{'day': 'Monday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Tuesday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Wednesday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Thursday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Friday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Saturday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Sunday', 'hours': '7\u202fAM to 10\u202fPM'}], 'reviewsCount': 216, 'additionalInfo': {'Pets': [{'Dogs allowed': True}], 'Crowd': [{'College students': True}, {'Groups': True}], 'Parking': [{'Free parking lot': True}, {'Free street parking': True}, {'Usually plenty of parking': True}], 'Children': [{'Good for kids': True}], 'Payments': [{'Credit cards': True}], 'Amenities': [{'Restroom': True}], 'Offerings': [{'Coffee': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}, {'Quiet': True}, {'Romantic': True}], 'Highlights': [{'Great coffee': True}, {'Great tea selection': True}], 'Popular for': [{'Good for working on laptop': True}], 'Accessibility': [{'Wheelchair accessible seating': True}], 'Dining options': [{'Catering': True}, {'Seating': True}, {'Table service': True}], 'Service options': [{'Outdoor seating': True}, {'Delivery': True}, {'Takeout': True}, {'Dine-in': True}]}})])
RealDictRow([('metadata', {'city': 'Ho Chi Minh City', 'poiType': ['Coffee shop'], 'totalScore': 5, 'imagesCount': 88, 'openingHours': [{'day': 'Monday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Tuesday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Wednesday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Thursday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Friday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Saturday', 'hours': '7\u202fAM to 10\u202fPM'}, {'day': 'Sunday', 'hours': '7\u202fAM to 10\u202fPM'}], 'reviewsCount': 275, 'additionalInfo': {'Crowd': [{'College students': True}, {'Groups': True}], 'Parking': [{'Free parking lot': True}, {'Free street parking': True}, {'Usually plenty of parking': True}], 'Payments': [{'Credit cards': True}, {'Debit cards': True}, {'NFC mobile payments': True}], 'Amenities': [{'Restroom': True}], 'Offerings': [{'Coffee': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}], 'Highlights': [{'Great coffee': True}, {'Great tea selection': True}], 'Popular for': [{'Good for working on laptop': True}], 'Dining options': [{'Catering': True}, {'Seating': True}, {'Table service': True}], 'Service options': [{'Outdoor seating': True}, {'Takeout': True}, {'Dine-in': True}]}})])
RealDictRow([('metadata', {'city': 'Málaga', 'poiType': ['Italian restaurant', 'Bar & grill', 'Cocktail bar', 'Family restaurant', 'Northern Italian restaurant', 'Pizza delivery', 'Pizza restaurant', 'Pizza Takeout', 'Restaurant', 'Southern Italian restaurant'], 'additionalInfo': {'Crowd': [{'Family-friendly': True}, {'Groups': True}, {'Tourists': True}], 'Parking': [{'Free parking lot': True}, {'Free street parking': True}], 'Children': [{'Good for kids': True}, {'High chairs': True}, {"Kids' menu": True}], 'Payments': [{'Credit cards': True}, {'Debit cards': True}, {'NFC mobile payments': True}], 'Planning': [{'Lunch reservations recommended': True}, {'Dinner reservations recommended': True}, {'Accepts reservations': True}], 'Amenities': [{'Bar onsite': True}, {'Restroom': True}, {'Wi-Fi': True}, {'Free Wi-Fi': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Coffee': True}, {'Hard liquor': True}, {'Healthy options': True}, {'Salad bar': True}, {'Wine': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}, {'Quiet': True}, {'Trendy': True}], 'Highlights': [{'Great coffee': True}, {'Great dessert': True}, {'Great wine list': True}], 'Popular for': [{'Lunch': True}, {'Dinner': True}, {'Solo dining': True}], 'Accessibility': [{'Wheelchair accessible entrance': True}, {'Wheelchair accessible restroom': True}, {'Wheelchair accessible seating': True}], 'Dining options': [{'Lunch': True}, {'Dinner': True}, {'Dessert': True}, {'Seating': True}, {'Table service': True}], 'Service options': [{'Outdoor seating': True}, {'Delivery': True}, {'Takeout': True}, {'Dine-in': True}]}})])
RealDictRow([('metadata', {'city': 'Málaga', 'poiType': ['Disco club', 'Bar', 'Night club'], 'additionalInfo': {'Crowd': [{'Groups': True}, {'LGBTQ+ friendly': True}, {'Transgender safespace': True}], 'Payments': [{'Credit cards': True}, {'Debit cards': True}, {'NFC mobile payments': True}, {'Credit cards': True}], 'Planning': [{'Accepts reservations': True}], 'Amenities': [{'Restroom': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Dancing': True}, {'Hard liquor': True}, {'Wine': True}], 'Atmosphere': [{'Trendy': True}], 'Highlights': [{'Great cocktails': True}, {'Karaoke': True}], 'Accessibility': [{'Wheelchair accessible entrance': True}, {'Wheelchair accessible restroom': True}, {'Assistive hearing loop': False}, {'Wheelchair accessible parking lot': False}, {'Wheelchair accessible seating': False}], 'Dining options': [{'Table service': False}], 'Service options': [{'Onsite services': True}, {'Delivery': False}, {'Takeout': False}]}})])

In [9]:
def extract_true_keys(items):
    if not isinstance(items, list):
        return []
    return [
        key
        for d in items if isinstance(d, dict)
        for key, value in d.items()
        if value is True
    ]

In [10]:
crowd = []
offerings = []
atmosphere = []
highlights = []
dining_options = []
children = []
accessibility = []
popular_for = []

for poi in rows:
    metadata = poi.get("metadata") or {}
    additional = metadata.get("additionalInfo") or {}

    if not isinstance(additional, dict):
        continue

    crowd.append(extract_true_keys(additional.get("Crowd")))
    offerings.append(extract_true_keys(additional.get("Offerings")))
    atmosphere.append(extract_true_keys(additional.get("Atmosphere")))
    highlights.append(extract_true_keys(additional.get("Highlights")))
    dining_options.append(extract_true_keys(additional.get("Dining options")))
    children.append(extract_true_keys(additional.get("Children")))
    accessibility.append(extract_true_keys(additional.get("Accessibility")))
    popular_for.append(extract_true_keys(additional.get("Popular for")))

In [11]:
print("Crowd:", len(crowd))
print("Offerings:", len(offerings))
print("Atmosphere:", len(atmosphere))
print("Highlights:", len(highlights))
print("Dining options:", len(dining_options))
print("Children:", len(children))
print("Accessibility:", len(accessibility))
print("Popular for:", len(popular_for))

Crowd: 1454
Offerings: 1454
Atmosphere: 1454
Highlights: 1454
Dining options: 1454
Children: 1454
Accessibility: 1454
Popular for: 1454

In [12]:
print(crowd[:10])
print(offerings[:10])
print(atmosphere[:10])
print(highlights[:10])
print(dining_options[:10])
print(children[:10])
print(accessibility[:10])
print(popular_for[:10])

[['Groups'], ['College students', 'Groups', 'Tourists'], ['Family-friendly', 'Groups', 'LGBTQ+ friendly', 'Tourists'], [], ['Groups', 'LGBTQ+ friendly', 'Transgender safespace'], ['Groups', 'LGBTQ+ friendly', 'Tourists', 'Transgender safespace'], ['College students', 'Groups'], ['College students', 'Groups'], ['Family-friendly', 'Groups', 'Tourists'], ['Groups', 'LGBTQ+ friendly', 'Transgender safespace']]
[['Alcohol', 'Beer', 'Cocktails', 'Coffee', 'Hard liquor'], ['Alcohol', 'Beer', 'Coffee', 'Healthy options', 'Organic dishes', 'Prepared foods', 'Quick bite', 'Vegan options', 'Vegetarian options', 'Wine'], ['Alcohol', 'Beer', 'Cocktails', 'Coffee', 'Happy hour drinks', 'Hard liquor', 'Small plates', 'Vegetarian options', 'Wine'], [], ['Alcohol', 'Beer', 'Cocktails', 'Food', 'Happy hour drinks', 'Happy hour food', 'Hard liquor', 'Wine'], ['Alcohol', 'Cocktails', 'Food', 'Food at bar', 'Hard liquor', 'Wine'], ['Coffee'], ['Coffee'], ['Alcohol', 'Beer', 'Cocktails', 'Coffee', 'Hard liquor', 'Healthy options', 'Salad bar', 'Wine'], ['Alcohol', 'Beer', 'Cocktails', 'Dancing', 'Hard liquor', 'Wine']]
[['Casual', 'Cozy'], ['Casual', 'Cozy', 'Trendy'], ['Casual', 'Cozy', 'Romantic'], [], ['Casual'], ['Cozy'], ['Casual', 'Cozy', 'Quiet', 'Romantic'], ['Casual', 'Cozy'], ['Casual', 'Cozy', 'Quiet', 'Trendy'], ['Trendy']]
[['Great beer selection', 'Great coffee', 'Live music', 'Live performances'], ['Great coffee', 'Great dessert', 'Great tea selection'], ['Great beer selection', 'Great cocktails', 'Great coffee', 'Great dessert', 'Great wine list', 'Rooftop seating'], [], ['Live music', 'Live performances'], ['Bar games', 'Great cocktails', 'Live performances'], ['Great coffee', 'Great tea selection'], ['Great coffee', 'Great tea selection'], ['Great coffee', 'Great dessert', 'Great wine list'], ['Great cocktails', 'Karaoke']]
[['Table service'], ['Breakfast', 'Brunch', 'Lunch', 'Dessert', 'Seating', 'Table service'], ['Brunch', 'Lunch', 'Dinner', 'Catering', 'Counter service', 'Dessert', 'Seating', 'Table service'], [], ['Seating', 'Table service'], ['Seating', 'Table service'], ['Catering', 'Seating', 'Table service'], ['Catering', 'Seating', 'Table service'], ['Lunch', 'Dinner', 'Dessert', 'Seating', 'Table service'], []]
[[], ['Good for kids'], ['Good for kids'], [], [], [], ['Good for kids'], [], ['Good for kids', 'High chairs', "Kids' menu"], []]
[[], ['Wheelchair accessible entrance', 'Wheelchair accessible restroom', 'Wheelchair accessible seating'], ['Wheelchair accessible seating'], ['Wheelchair accessible entrance'], [], ['Wheelchair accessible entrance', 'Wheelchair accessible parking lot', 'Wheelchair accessible seating'], ['Wheelchair accessible seating'], [], ['Wheelchair accessible entrance', 'Wheelchair accessible restroom', 'Wheelchair accessible seating'], ['Wheelchair accessible entrance', 'Wheelchair accessible restroom']]
[[], ['Breakfast', 'Good for working on laptop'], ['Lunch', 'Dinner', 'Solo dining'], [], [], [], ['Good for working on laptop'], ['Good for working on laptop'], ['Lunch', 'Dinner', 'Solo dining'], []]

In [14]:
file_path = os.path.join(os.getcwd(), "data/data_clean_normalize.csv")
df = pd.read_csv(file_path, encoding="utf-8")
df.head()

,id,name,address,lat,lon,poi_type,avg_stars,total_reviews,stay_time,normalize_stars_reviews,crowd,offerings,atmosphere,highlights,dining_options
0,0f9d2009-9436-46a4-b354-b0261898a39e,The Pub Coffee - Beer & Cocktail,"18A17 Tăng Nhơn Phú, Phước Long B, Quận 9, Thà...",10.829481,106.773785,"Cafe,Bar",4.9,181,30,0.755,Groups,"Alcohol, Beer, Cocktails, Coffee, Hard liquor","Casual, Cozy","Great beer selection, Great coffee, Live music...",Table service
1,02887955-963a-43ac-b0f7-355d7d7cfacf,Julieta,"C. Sta. Lucía, 9, Distrito Centro, 29008 Málag...",36.722011,-4.421780,Cafe,4.3,2053,30,0.661,"College students, Groups, Tourists","Alcohol, Beer, Coffee, Healthy options, Organi...","Casual, Cozy, Trendy","Great coffee, Great dessert, Great tea selection","Breakfast, Brunch, Lunch, Dessert, Seating, Ta..."
2,622c7643-30e8-4402-9b6c-b8407ff063e2,BAIETA Restaurant Saigon Thao Dien,"Nguyễn Văn Hưởng, Thảo Điền, 16/8, Thành phố H...",10.802978,106.727268,"Restaurant,Bar,Cocktail bar,Coffee shop,Family...",4.5,285,30,0.651,"Family-friendly, Groups, LGBTQ+ friendly, Tour...","Alcohol, Beer, Cocktails, Coffee, Happy hour d...","Casual, Cozy, Romantic","Great beer selection, Great cocktails, Great c...","Brunch, Lunch, Dinner, Catering, Counter servi..."
3,4f06908d-e9fa-4f6a-b1ae-c7d8882e2edf,Parroquia San Felipe Neri,"C. Guerrero, 6, Distrito Centro, 29012 Málaga,...",36.725554,-4.421321,"Catholic church,Tourist attraction",4.7,329,30,0.716,NaN,NaN,NaN,NaN,NaN
4,279dfce3-c227-4b58-b4ed-09197327a32a,BÀ BAR,"15 Đ. Nguyễn Cừ, Thảo Điền, Quận 2, Thành phố ...",10.803190,106.728381,"Cocktail bar,Cafe",4.8,182,30,0.725,"Groups, LGBTQ+ friendly, Transgender safespace","Alcohol, Beer, Cocktails, Food, Happy hour dri...",Casual,"Live music, Live performances","Seating, Table service"

In [110]:
df["crowd"] = [", ".join(c) for c in crowd]
df["offerings"] = [", ".join(c) for c in offerings]
df["atmosphere"] = [", ".join(c) for c in atmosphere]
df["highlights"] = [", ".join(c) for c in highlights]
df["dining_options"] = [", ".join(c) for c in dining_options]
df["children"] = [", ".join(c) for c in children]
df["accessibility"] = [", ".join(c) for c in accessibility]
df["popular_for"] = [", ".join(c) for c in popular_for]

In [16]:
df.head()

,id,name,address,lat,lon,poi_type,avg_stars,total_reviews,stay_time,normalize_stars_reviews,crowd,offerings,atmosphere,highlights,dining_options
0,0f9d2009-9436-46a4-b354-b0261898a39e,The Pub Coffee - Beer & Cocktail,"18A17 Tăng Nhơn Phú, Phước Long B, Quận 9, Thà...",10.829481,106.773785,"Cafe,Bar",4.9,181,30,0.755,[Groups],"Alcohol, Beer, Cocktails, Coffee, Hard liquor","Casual, Cozy","Great beer selection, Great coffee, Live music...",Table service
1,02887955-963a-43ac-b0f7-355d7d7cfacf,Julieta,"C. Sta. Lucía, 9, Distrito Centro, 29008 Málag...",36.722011,-4.421780,Cafe,4.3,2053,30,0.661,"[College students, Groups, Tourists]","Alcohol, Beer, Coffee, Healthy options, Organi...","Casual, Cozy, Trendy","Great coffee, Great dessert, Great tea selection","Breakfast, Brunch, Lunch, Dessert, Seating, Ta..."
2,622c7643-30e8-4402-9b6c-b8407ff063e2,BAIETA Restaurant Saigon Thao Dien,"Nguyễn Văn Hưởng, Thảo Điền, 16/8, Thành phố H...",10.802978,106.727268,"Restaurant,Bar,Cocktail bar,Coffee shop,Family...",4.5,285,30,0.651,"[Family-friendly, Groups, LGBTQ+ friendly, Tou...","Alcohol, Beer, Cocktails, Coffee, Happy hour d...","Casual, Cozy, Romantic","Great beer selection, Great cocktails, Great c...","Brunch, Lunch, Dinner, Catering, Counter servi..."
3,4f06908d-e9fa-4f6a-b1ae-c7d8882e2edf,Parroquia San Felipe Neri,"C. Guerrero, 6, Distrito Centro, 29012 Málaga,...",36.725554,-4.421321,"Catholic church,Tourist attraction",4.7,329,30,0.716,[],NaN,NaN,NaN,NaN
4,279dfce3-c227-4b58-b4ed-09197327a32a,BÀ BAR,"15 Đ. Nguyễn Cừ, Thảo Điền, Quận 2, Thành phố ...",10.803190,106.728381,"Cocktail bar,Cafe",4.8,182,30,0.725,"[Groups, LGBTQ+ friendly, Transgender safespace]","Alcohol, Beer, Cocktails, Food, Happy hour dri...",Casual,"Live music, Live performances","Seating, Table service"

In [ ]:
df.to_csv("data/data_final.csv", index=False)

# Thêm openingHours

In [ ]:
# openingHours từ raw_data

In [11]:
cur.execute('SELECT raw_data FROM "Poi"')
rows = cur.fetchall()
for poi in rows[:10]:
    print(poi)

RealDictRow([('raw_data', {'google': {'cid': '9137476420856649765', 'fid': '0x317527b418461fed:0x7eced66470ab1825', 'url': 'https://www.google.com/maps/search/?api=1&query=The%20Pub%20Coffee%20-%20Beer%20%26%20Cocktail&query_place_id=ChIJ7R9GGLQndTERJRircGTWzn4', 'city': 'Ho Chi Minh City', 'menu': None, 'rank': 1, 'kgmid': '/g/11fpkvlhz2', 'phone': '+84 974 188 353', 'price': None, 'state': 'Quận 9, Ho Chi Minh City', 'title': 'The Pub Coffee - Beer & Cocktail', 'emails': [], 'images': None, 'phones': [], 'street': '18A17 Tăng Nhơn Phú', 'address': '18A17 Tăng Nhơn Phú, Phước Long B, Quận 9, Thành phố Hồ Chí Minh, Vietnam', 'orderBy': [], 'placeId': 'ChIJ7R9GGLQndTERJRircGTWzn4', 'reviews': [{'name': 'Thảo Thanh', 'text': 'Quán rộng rãi thoáng mát, giá cả sinh viên', 'stars': 5, 'rating': None, 'reviewId': 'Ci9DQUlRQUNvZENodHljRjlvT21WaFR6QTVTblptZDBWQmRISTVTSFptYm1STmFsRRAB', 'publishAt': 'a week ago', 'reviewUrl': 'https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21WaFR6QTVTblptZDBWQmRISTVTSFptYm1STmFsRRAB!2m1!1s0x0:0x7eced66470ab1825!3m1!1s2@1:CAIQACodChtycF9oOmVhTzA5SnZmd0VBdHI5SHZmbmRNalE%7C0d7_fx6BhHa%7C?hl=en', 'visitedIn': None, 'likesCount': 0, 'reviewerId': '101403667203806476656', 'reviewerUrl': 'https://www.google.com/maps/contrib/101403667203806476656?hl=en', 'isLocalGuide': False, 'reviewOrigin': 'Google', 'reviewContext': {}, 'textTranslated': 'Spacious and airy restaurant, student prices', 'publishedAtDate': '2025-11-23T00:53:17.120Z', 'reviewImageUrls': [], 'originalLanguage': 'vi', 'reviewerPhotoUrl': 'https://lh3.googleusercontent.com/a-/ALV-UjVzeWGK5_Oz2BrxR6WCrbY9bc3mJIXiDYqsbcMI-T3QqaGihcU=s1920-c-rp-mo-br100', 'translatedLanguage': 'en', 'reviewDetailedRating': {'Food': 5, 'Service': 5, 'Atmosphere': 5}, 'responseFromOwnerDate': None, 'responseFromOwnerText': None, 'reviewerNumberOfReviews': 1}, {'name': 'Hieu Pham', 'text': 'Anh nhân viên Trọng Trí quá tuyệt vời', 'stars': 5, 'rating': None, 'reviewId': 'Ci9DQUlRQUNvZENodHljRjlvT2xWRGJtRktXVXMyVWpObmNISlhZVkpaVDNNNGIxRRAB', 'publishAt': '3 weeks ago', 'reviewUrl': 'https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xWRGJtRktXVXMyVWpObmNISlhZVkpaVDNNNGIxRRAB!2m1!1s0x0:0x7eced66470ab1825!3m1!1s2@1:CAIQACodChtycF9oOlVDbmFKWUs2UjNncHJXYVJZT3M4b1E%7C0d3ZEkoVNLU%7C?hl=en', 'visitedIn': None, 'likesCount': 0, 'reviewerId': '112143220850485916789', 'reviewerUrl': 'https://www.google.com/maps/contrib/112143220850485916789?hl=en', 'isLocalGuide': False, 'reviewOrigin': 'Google', 'reviewContext': {}, 'textTranslated': 'Mr. Trong Tri is so wonderful', 'publishedAtDate': '2025-11-10T19:58:40.880Z', 'reviewImageUrls': [], 'originalLanguage': 'vi', 'reviewerPhotoUrl': 'https://lh3.googleusercontent.com/a/ACg8ocI6rvAvZogUUJeUse1iVbUcHT7WoSkI_abokT01Fm2ZQDqvaA=s1920-c-rp-mo-br100', 'translatedLanguage': 'en', 'reviewDetailedRating': {'Food': 5, 'Service': 5, 'Atmosphere': 5}, 'responseFromOwnerDate': '2025-11-22T07:19:37.000Z', 'responseFromOwnerText': 'Phải k đó để biết thưởng nóng cho ẻm', 'reviewerNumberOfReviews': 2}, {'name': 'Oanh Phạm Thị Kiều', 'text': 'quán view thoáng, nhiệt tình, đồ uống siêu ngon ạ', 'stars': 5, 'rating': None, 'reviewId': 'Ci9DQUlRQUNvZENodHljRjlvT2pWVGFsUlpORVpPVjBjd1JGcHFWRzVoWDJocGJYYxAB', 'publishAt': 'a month ago', 'reviewUrl': 'https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2pWVGFsUlpORVpPVjBjd1JGcHFWRzVoWDJocGJYYxAB!2m1!1s0x0:0x7eced66470ab1825!3m1!1s2@1:CAIQACodChtycF9oOjVTalRZNEZOV0cwRFpqVG5hX2hpbXc%7C0d0L337MKzu%7C?hl=en', 'visitedIn': None, 'likesCount': 0, 'reviewerId': '110275962475137145795', 'reviewerUrl': 'https://www.google.com/maps/contrib/110275962475137145795?hl=en', 'isLocalGuide': False, 'reviewOrigin': 'Google', 'reviewContext': {'Group size': 'Suitable for all group sizes'}, 'textTranslated': 'The shop has a great view, friendly staff, and delicious drinks.', 'publishedAtDate': '2025-11-01T01:23:16.140Z', 'reviewImageUrls': [], 'originalLanguage': 'vi', 'reviewerPhotoUrl': 'https://lh3.googleusercontent.com/a/ACg8ocLQWY4nD9u2fbL_I65qpCwfGNRzIXKvmTv5bL2cLWNwaBdqBw=s1920-c-rp-mo-br100', 'translatedLanguage': 'en', 'reviewDetailedRating': {}, 'responseFromOwnerDate': '2025-11-22T07:19:06.000Z', 'responseFromOwnerText': 'Trái tim', 'reviewerNumberOfReviews': 2}], 'tiktoks': [], 'website': None, 'discords': [], 'hotelAds': [], 'imageUrl': 'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwlrYb68I8vRz1MIT8NEv_cCZidFtKMqJ_xB8G6jiYDrgU1EREBbOFiNYM4_Y05EVMzZXRR_0SRam-x93cwTPhtLS3lU_gwRIV-Zm6xrNeAXKCFxaYCvwJ3LPk3QONPdVJ0-zev=w408-h544-k-no', 'language': 'en', 'location': {'lat': 10.8294811, 'lng': 106.7737852}, 'plusCode': 'RQHF+QG Thủ Đức City, Ho Chi Minh City, Vietnam', 'subTitle': None, 'twitters': [], 'youtubes': [], 'facebooks': [], 'gasPrices': [], 'imageUrls': ['https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwlrYb68I8vRz1MIT8NEv_cCZidFtKMqJ_xB8G6jiYDrgU1EREBbOFiNYM4_Y05EVMzZXRR_0SRam-x93cwTPhtLS3lU_gwRIV-Zm6xrNeAXKCFxaYCvwJ3LPk3QONPdVJ0-zev=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipNl1ba0rtKO17wm_8_eyko_nPJnHu0aieMni07w=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipMahGH6wS4tt8l-p8Yf4ctUVAA2cc5ibp1YpY00=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipOqjUr0DosL1PfpAl4qsXnhZpmttzBtMX1nveM_=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz8EQWZDqU5ua6GLl33qkUB62NXKyLwx8yfFs6hbrHwnvg4js--Snu95_8c2lPhfinVQJRYMtpBvx8ZbWrjmc-Uzk4Zhp4Gv6zKTnwh9TwEexoK0-03qKyWC9GIb9x4dVu-PEsVuw=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyw6fqGYYHgt4xBgOoOvNT6AVehhlKTy3rXQwQHbOCpSYrM2h1bVxl_TgDjyhmjGYIJY_fkA58HnkE1MD36OqpLR5so_xTsiKULN81IwVvCKZh0PPBArKl_-De3PP_qLwaPU7Zk=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipMY2EOVvNFixS5sIfqIpNqU8wlPccUJZR8_hGO1=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipOS5w7PWsZNheE364HleK0_EMLtNLTJytfX0NTN=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipM97WK1fYF1jXcN0e4UMbMNJlB4OSBxGDEIQCyi=w1920-h1080-k-no', 'https://lh3.googleusercontent.com/p/AF1QipOB61ysyrxH5izxZ5AEXKngWKtXTcq7qvkIWR3e=w1920-h1080-k-no'], 'linkedIns': [], 'locatedIn': None, 'scrapedAt': '2025-12-05T04:26:35.491Z', 'categories': ['Cafe', 'Bar'], 'hotelStars': None, 'instagrams': [], 'pinterests': [], 'placesTags': [], 'postalCode': None, 'totalScore': 4.9, 'webResults': [], 'checkInDate': None, 'countryCode': 'VN', 'description': None, 'imagesCount': 55, 'reviewsTags': [], 'bookingLinks': [], 'categoryName': 'Cafe', 'checkOutDate': None, 'inputPlaceId': None, 'neighborhood': 'Phước Long B, Quận 9', 'openingHours': [{'day': 'Monday', 'hours': 'Open 24 hours'}, {'day': 'Tuesday', 'hours': 'Open 24 hours'}, {'day': 'Wednesday', 'hours': 'Open 24 hours'}, {'day': 'Thursday', 'hours': 'Open 24 hours'}, {'day': 'Friday', 'hours': 'Open 24 hours'}, {'day': 'Saturday', 'hours': 'Open 24 hours'}, {'day': 'Sunday', 'hours': 'Open 24 hours'}], 'ownerUpdates': [], 'reviewsCount': 181, 'searchString': 'pub', 'googleFoodUrl': None, 'searchPageUrl': 'https://www.google.com/maps/search/pub/@10.859038390216558,106.75577809191171,13z?hl=en', 'userPlaceNote': None, 'additionalInfo': {'Crowd': [{'Groups': True}], 'Payments': [{'NFC mobile payments': True}], 'Planning': [{'Accepts reservations': True}], 'Amenities': [{'Bar onsite': True}, {'Restroom': True}], 'Offerings': [{'Alcohol': True}, {'Beer': True}, {'Cocktails': True}, {'Coffee': True}, {'Hard liquor': True}], 'Atmosphere': [{'Casual': True}, {'Cozy': True}], 'Highlights': [{'Great beer selection': True}, {'Great coffee': True}, {'Live music': True}, {'Live performances': True}], 'Dining options': [{'Table service': True}], 'Service options': [{'No-contact delivery': True}, {'Delivery': True}, {'Drive-through': True}, {'Takeout': True}, {'Dine-in': True}]}, 'restaurantData': {'tableReservationProvider': None}, 'imageCategories': ['All', 'Menu', 'Videos', 'Food & drink', 'By owner', 'Street View & 360°'], 'isAdvertisement': False, 'leadsEnrichment': [], 'phonesUncertain': [], 'reserveTableUrl': None, 'hotelDescription': None, 'peopleAlsoSearch': [{'title': '39 𝐁𝐄𝐄𝐑 FOOD', 'category': 'People also search for', 'totalScore': 3.8, 'reviewsCount': 63}, {'title': 'Quán Bar', 'category': 'People also search for', 'totalScore': 5, 'reviewsCount': 3}, {'title': '99 Coffee Lounge', 'category': 'People also search for', 'totalScore': 4.5, 'reviewsCount': 10}, {'title': 'Mini Pod Cocktail Bar', 'category': 'People also search for', 'totalScore': 5, 'reviewsCount': 20}, {'title': 'Chill Beer 97', 'category': 'People also search for', 'totalScore': 3, 'reviewsCount': 1}], 'phoneUnformatted': '+84974188353', 'claimThisBusiness': False, 'permanentlyClosed': False, 'temporarilyClosed': False, 'hotelReviewSummary': None, 'questionsAndAnswers': [], 'reviewsDistribution': {'oneStar': 4, 'twoStar': 0, 'fiveStar': 175, 'fourStar': 2, 'threeStar': 0}, 'similarHotelsNearby': None, 'popularTimesLiveText': 'Now: Usually not too busy', 'updatesFromCustomers': None, 'popularTimesHistogram': {'Fr': [{'hour': 4, 'occupancyPercent': 81}, {'hour': 5, 'occupancyPercent': 75}, {'hour': 6, 'occupancyPercent': 68}, {'hour': 7, 'occupancyPercent': 62}, {'hour': 8, 'occupancyPercent': 50}, {'hour': 9, 'occupancyPercent': 37}, {'hour': 10, 'occupancyPercent': 37}, {'hour': 11, 'occupancyPercent': 25}, {'hour': 12, 'occupancyPercent': 43}, {'hour': 13, 'occupancyPercent': 62}, {'hour': 14, 'occupancyPercent': 62}, {'hour': 15, 'occupancyPercent': 56}, {'hour': 16, 'occupancyPercent': 50}, {'hour': 17, 'occupancyPercent': 31}, {'hour': 18, 'occupancyPercent': 18}, {'hour': 19, 'occupancyPercent': 18}, {'hour': 20, 'occupancyPercent': 37}, {'hour': 21, 'occupancyPercent': 43}, {'hour': 22, 'occupancyPercent': 68}, {'hour': 23, 'occupancyPercent': 75}, {'hour': 0, 'occupancyPercent': 68}, {'hour': 1, 'occupancyPercent': 50}, {'hour': 2, 'occupancyPercent': 43}, {'hour': 3, 'occupancyPercent': 50}], 'Mo': [{'hour': 4, 'occupancyPercent': 25}, {'hour': 5, 'occupancyPercent': 25}, {'hour': 6, 'occupancyPercent': 18}, {'hour': 7, 'occupancyPercent': 12}, {'hour': 8, 'occupancyPercent': 18}, {'hour': 9, 'occupancyPercent': 12}, {'hour': 10, 'occupancyPercent': 31}, {'hour': 11, 'occupancyPercent': 37}, {'hour': 12, 'occupancyPercent': 50}, {'hour': 13, 'occupancyPercent': 50}, {'hour': 14, 'occupancyPercent': 87}, {'hour': 15, 'occupancyPercent': 50}, {'hour': 16, 'occupancyPercent': 50}, {'hour': 17, 'occupancyPercent': 43}, {'hour': 18, 'occupancyPercent': 37}, {'hour': 19, 'occupancyPercent': 56}, {'hour': 20, 'occupancyPercent': 37}, {'hour': 21, 'occupancyPercent': 43}, {'hour': 22, 'occupancyPercent': 37}, {'hour': 23, 'occupancyPercent': 56}, {'hour': 0, 'occupancyPercent': 50}, {'hour': 1, 'occupancyPercent': 31}, {'hour': 2, 'occupancyPercent': 18}, {'hour': 3, 'occupancyPercent': 25}], 'Sa': [{'hour': 4, 'occupancyPercent': 37}, {'hour': 5, 'occupancyPercent': 56}, {'hour': 6, 'occupancyPercent': 68}, {'hour': 7, 'occupancyPercent': 93}, {'hour': 8, 'occupancyPercent': 81}, {'hour': 9, 'occupancyPercent': 75}, {'hour': 10, 'occupancyPercent': 81}, {'hour': 11, 'occupancyPercent': 43}, {'hour': 12, 'occupancyPercent': 56}, {'hour': 13, 'occupancyPercent': 50}, {'hour': 14, 'occupancyPercent': 75}, {'hour': 15, 'occupancyPercent': 50}, {'hour': 16, 'occupancyPercent': 37}, {'hour': 17, 'occupancyPercent': 25}, {'hour': 18, 'occupancyPercent': 31}, {'hour': 19, 'occupancyPercent': 43}, {'hour': 20, 'occupancyPercent': 62}, {'hour': 21, 'occupancyPercent': 81}, {'hour': 22, 'occupancyPercent': 75}, {'hour': 23, 'occupancyPercent': 68}, {'hour': 0, 'occupancyPercent': 50}, {'hour': 1, 'occupancyPercent': 37}, {'hour': 2, 'occupancyPercent': 31}, {'hour': 3, 'occupancyPercent': 43}], 'Su': [{'hour': 4, 'occupancyPercent': 31}, {'hour': 5, 'occupancyPercent': 50}, {'hour': 6, 'occupancyPercent': 68}, {'hour': 7, 'occupancyPercent': 62}, {'hour': 8, 'occupancyPercent': 43}, {'hour': 9, 'occupancyPercent': 18}, {'hour': 10, 'occupancyPercent': 6}, {'hour': 11, 'occupancyPercent': 0}, {'hour': 12, 'occupancyPercent': 12}, {'hour': 13, 'occupancyPercent': 25}, {'hour': 14, 'occupancyPercent': 43}, {'hour': 15, 'occupancyPercent': 56}, {'hour': 16, 'occupancyPercent': 43}, {'hour': 17, 'occupancyPercent': 50}, {'hour': 18, 'occupancyPercent': 43}, {'hour': 19, 'occupancyPercent': 56}, {'hour': 20, 'occupancyPercent': 75}, {'hour': 21, 'occupancyPercent': 87}, {'hour': 22, 'occupancyPercent': 68}, {'hour': 23, 'occupancyPercent': 56}, {'hour': 0, 'occupancyPercent': 62}, {'hour': 1, 'occupancyPercent': 75}, {'hour': 2, 'occupancyPercent': 62}, {'hour': 3, 'occupancyPercent': 50}], 'Th': [{'hour': 4, 'occupancyPercent': 43}, {'hour': 5, 'occupancyPercent': 37}, {'hour': 6, 'occupancyPercent': 37}, {'hour': 7, 'occupancyPercent': 31}, {'hour': 8, 'occupancyPercent': 25}, {'hour': 9, 'occupancyPercent': 25}, {'hour': 10, 'occupancyPercent': 31}, {'hour': 11, 'occupancyPercent': 43}, {'hour': 12, 'occupancyPercent': 50}, {'hour': 13, 'occupancyPercent': 31}, {'hour': 14, 'occupancyPercent': 18}, {'hour': 15, 'occupancyPercent': 6}, {'hour': 16, 'occupancyPercent': 6}, {'hour': 17, 'occupancyPercent': 25}, {'hour': 18, 'occupancyPercent': 43}, {'hour': 19, 'occupancyPercent': 50}, {'hour': 20, 'occupancyPercent': 56}, {'hour': 21, 'occupancyPercent': 43}, {'hour': 22, 'occupancyPercent': 31}, {'hour': 23, 'occupancyPercent': 43}, {'hour': 0, 'occupancyPercent': 37}, {'hour': 1, 'occupancyPercent': 31}, {'hour': 2, 'occupancyPercent': 25}, {'hour': 3, 'occupancyPercent': 37}], 'Tu': [{'hour': 4, 'occupancyPercent': 37}, {'hour': 5, 'occupancyPercent': 37}, {'hour': 6, 'occupancyPercent': 31}, {'hour': 7, 'occupancyPercent': 31}, {'hour': 8, 'occupancyPercent': 12}, {'hour': 9, 'occupancyPercent': 12}, {'hour': 10, 'occupancyPercent': 12}, {'hour': 11, 'occupancyPercent': 18}, {'hour': 12, 'occupancyPercent': 43}, {'hour': 13, 'occupancyPercent': 56}, {'hour': 14, 'occupancyPercent': 62}, {'hour': 15, 'occupancyPercent': 37}, {'hour': 16, 'occupancyPercent': 31}, {'hour': 17, 'occupancyPercent': 25}, {'hour': 18, 'occupancyPercent': 18}, {'hour': 19, 'occupancyPercent': 31}, {'hour': 20, 'occupancyPercent': 37}, {'hour': 21, 'occupancyPercent': 37}, {'hour': 22, 'occupancyPercent': 43}, {'hour': 23, 'occupancyPercent': 43}, {'hour': 0, 'occupancyPercent': 62}, {'hour': 1, 'occupancyPercent': 50}, {'hour': 2, 'occupancyPercent': 37}, {'hour': 3, 'occupancyPercent': 25}], 'We': [{'hour': 4, 'occupancyPercent': 43}, {'hour': 5, 'occupancyPercent': 18}, {'hour': 6, 'occupancyPercent': 12}, {'hour': 7, 'occupancyPercent': 25}, {'hour': 8, 'occupancyPercent': 56}, {'hour': 9, 'occupancyPercent': 87}, {'hour': 10, 'occupancyPercent': 100}, {'hour': 11, 'occupancyPercent': 87}, {'hour': 12, 'occupancyPercent': 75}, {'hour': 13, 'occupancyPercent': 56}, {'hour': 14, 'occupancyPercent': 50}, {'hour': 15, 'occupancyPercent': 43}, {'hour': 16, 'occupancyPercent': 31}, {'hour': 17, 'occupancyPercent': 18}, {'hour': 18, 'occupancyPercent': 18}, {'hour': 19, 'occupancyPercent': 37}, {'hour': 20, 'occupancyPercent': 75}, {'hour': 21, 'occupancyPercent': 56}, {'hour': 22, 'occupancyPercent': 37}, {'hour': 23, 'occupancyPercent': 12}, {'hour': 0, 'occupancyPercent': 6}, {'hour': 1, 'occupancyPercent': 18}, {'hour': 2, 'occupancyPercent': 31}, {'hour': 3, 'occupancyPercent': 37}]}, 'tableReservationLinks': [], 'additionalOpeningHours': None, 'popularTimesLivePercent': None, 'openingHoursBusinessConfirmationText': None}, 'social': {'tiktok': [], 'youtube': [], 'instagram': []}})])

## Xử lí xóa \u202f

In [44]:
def clean_opening_hours(data):
    cleaned = []
    for items in data:
        cleaned_items = []
        for i in items:
            cleaned_items.append({
                "day": i["day"],
                "hours": i["hours"].replace("\u202f", " ")
            })
        cleaned.append(cleaned_items)
    return cleaned

In [45]:
opening_hours = []

for poi in rows:
    raw_data = poi.get("raw_data") 
    google = raw_data.get("google")
    openingHours = google.get("openingHours")
    opening_hours.append(openingHours)

In [67]:
result =  clean_opening_hours(opening_hours)
print(result[0])
print(result[21])
print(result[22])

[{'day': 'Monday', 'hours': 'Open 24 hours'}, {'day': 'Tuesday', 'hours': 'Open 24 hours'}, {'day': 'Wednesday', 'hours': 'Open 24 hours'}, {'day': 'Thursday', 'hours': 'Open 24 hours'}, {'day': 'Friday', 'hours': 'Open 24 hours'}, {'day': 'Saturday', 'hours': 'Open 24 hours'}, {'day': 'Sunday', 'hours': 'Open 24 hours'}]
[{'day': 'Monday', 'hours': '8 to 11 PM'}, {'day': 'Tuesday', 'hours': '1:30 to 4 PM, 8 to 11 PM'}, {'day': 'Wednesday', 'hours': 'Closed'}, {'day': 'Thursday', 'hours': '1:30 to 4 PM, 8 to 11 PM'}, {'day': 'Friday', 'hours': '1:30 to 4 PM, 8 to 11 PM'}, {'day': 'Saturday', 'hours': '1:30 to 4 PM, 8 to 11 PM'}, {'day': 'Sunday', 'hours': 'Closed'}]
[{'day': 'Monday', 'hours': 'Closed'}, {'day': 'Tuesday', 'hours': '7:30 AM to 8 PM'}, {'day': 'Wednesday', 'hours': '7:30 AM to 8 PM'}, {'day': 'Thursday', 'hours': '7:30 AM to 8 PM'}, {'day': 'Friday', 'hours': '7:30 AM to 8 PM'}, {'day': 'Saturday', 'hours': '5:30 AM to 8:30 PM'}, {'day': 'Sunday', 'hours': '5:30 AM to 8:30 PM'}]

In [46]:
print(len(opening_hours))

1454

## Xử lí các trường hợp đặc biệt về thời gian cho openingHours

In [77]:
import re
from datetime import datetime

# ---- Helper: convert time string to 24h format ----
def to_24h(time_str, fallback_am_pm=None):
    time_str = time_str.strip()

    # If contains AM/PM → direct parse
    if "AM" in time_str.upper() or "PM" in time_str.upper():
        return datetime.strptime(time_str.upper(), "%I:%M %p").strftime("%H:%M") \
            if ":" in time_str else datetime.strptime(time_str.upper(), "%I %p").strftime("%H:%M")

    # If missing AM/PM, but fallback exists
    if fallback_am_pm:
        combined = f"{time_str} {fallback_am_pm}"
        try:
            return datetime.strptime(combined, "%I:%M %p").strftime("%H:%M") \
                if ":" in time_str else datetime.strptime(combined, "%I %p").strftime("%H:%M")
        except:
            pass

    # If totally unknown → assume 24h? But better skip
    return None


# ---- Main parser for hours ----
def parse_hours(hours_str):
    hours_str = hours_str.replace("\u202f", " ").strip()

    # Closed → skip
    if hours_str.lower() == "closed":
        return []

    # Open 24 hours
    if "open 24 hours" in hours_str.lower():
        return [{"start": "00:00", "end": "23:59"}]

    segments = [seg.strip() for seg in hours_str.split(",")]
    results = []

    for segment in segments:
        # Example segment: "1:30 to 4 PM"
        match = re.match(r"(.*) to (.*)", segment)
        if not match:
            continue

        start_raw, end_raw = match.groups()
        start_raw = start_raw.strip()
        end_raw = end_raw.strip()

        # Determine fallback AM/PM from end if start lacks AM/PM
        fallback = None
        if "AM" in end_raw.upper():
            fallback = "AM"
        if "PM" in end_raw.upper():
            fallback = "PM"

        start_24 = to_24h(start_raw, fallback)
        end_24 = to_24h(end_raw)

        if start_24 and end_24:
            results.append({
                "start": start_24,
                "end": end_24
            })

    return results


# ---- Main function to process full opening_hours array ----
def normalize_opening_hours(opening_hours):
    normalized = []

    for item in opening_hours:
        day = item["day"]
        hours = parse_hours(item["hours"])

        if hours:  # Skip closed days
            normalized.append({"day": day, "hours": hours})

    return normalized

def clean_opening_hours_special(data):
    cleaned_special = []
    for d in data:
        if len(d) == 0:
            cleaned_special.append([])
        else:
            item = normalize_opening_hours(d)
            cleaned_special.append(item)
    return cleaned_special

In [75]:
print(normalize_opening_hours(result[0]))
print(normalize_opening_hours(result[21]))
print(normalize_opening_hours(result[22]))

[{'day': 'Monday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Tuesday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Wednesday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Thursday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Friday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Saturday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Sunday', 'hours': [{'start': '00:00', 'end': '23:59'}]}]
[{'day': 'Monday', 'hours': [{'start': '20:00', 'end': '23:00'}]}, {'day': 'Tuesday', 'hours': [{'start': '13:30', 'end': '16:00'}, {'start': '20:00', 'end': '23:00'}]}, {'day': 'Thursday', 'hours': [{'start': '13:30', 'end': '16:00'}, {'start': '20:00', 'end': '23:00'}]}, {'day': 'Friday', 'hours': [{'start': '13:30', 'end': '16:00'}, {'start': '20:00', 'end': '23:00'}]}, {'day': 'Saturday', 'hours': [{'start': '13:30', 'end': '16:00'}, {'start': '20:00', 'end': '23:00'}]}]
[{'day': 'Tuesday', 'hours': [{'start': '07:30', 'end': '20:00'}]}, {'day': 'Wednesday', 'hours': [{'start': '07:30', 'end': '20:00'}]}, {'day': 'Thursday', 'hours': [{'start': '07:30', 'end': '20:00'}]}, {'day': 'Friday', 'hours': [{'start': '07:30', 'end': '20:00'}]}, {'day': 'Saturday', 'hours': [{'start': '05:30', 'end': '20:30'}]}, {'day': 'Sunday', 'hours': [{'start': '05:30', 'end': '20:30'}]}]

In [78]:
clean_opening_hours_special(result)

[[{'day': 'Monday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Tuesday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Wednesday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Thursday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Friday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Saturday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Sunday', 'hours': [{'start': '00:00', 'end': '23:59'}]}],
 [{'day': 'Monday', 'hours': [{'start': '08:00', 'end': '20:30'}]},
  {'day': 'Tuesday', 'hours': [{'start': '08:00', 'end': '20:30'}]},
  {'day': 'Wednesday', 'hours': [{'start': '08:00', 'end': '20:30'}]},
  {'day': 'Thursday', 'hours': [{'start': '08:00', 'end': '20:30'}]},
  {'day': 'Friday', 'hours': [{'start': '08:00', 'end': '20:30'}]},
  {'day': 'Saturday', 'hours': [{'start': '09:00', 'end': '20:30'}]},
  {'day': 'Sunday', 'hours': [{'start': '09:00', 'end': '20:30'}]}],
 [{'day': 'Tuesday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Friday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '11:30', 'end': '00:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '11:30', 'end': '00:00'}]}],
 [{'day': 'Tuesday', 'hours': [{'start': '17:30', 'end': '20:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '17:30', 'end': '20:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '17:30', 'end': '20:00'}]},
  {'day': 'Friday', 'hours': [{'start': '17:30', 'end': '20:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '17:30', 'end': '20:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '09:00', 'end': '13:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '10:00', 'end': '00:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '10:00', 'end': '00:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '10:00', 'end': '00:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '10:00', 'end': '00:00'}]},
  {'day': 'Friday', 'hours': [{'start': '10:00', 'end': '00:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '08:00', 'end': '00:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '08:00', 'end': '00:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Friday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '16:00', 'end': '00:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Friday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '07:00', 'end': '22:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Friday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '07:00', 'end': '22:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '07:00', 'end': '22:00'}]}],
 [{'day': 'Monday',
   'hours': [{'start': '13:30', 'end': '16:30'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Tuesday',
   'hours': [{'start': '13:30', 'end': '16:30'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Wednesday',
   'hours': [{'start': '13:30', 'end': '16:30'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Thursday',
   'hours': [{'start': '13:30', 'end': '16:30'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Friday',
   'hours': [{'start': '13:30', 'end': '16:30'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Saturday', 'hours': [{'start': '13:30', 'end': '23:30'}]},
  {'day': 'Sunday', 'hours': [{'start': '13:30', 'end': '23:30'}]}],
 [{'day': 'Tuesday', 'hours': [{'start': '22:00', 'end': '03:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '22:00', 'end': '03:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '22:00', 'end': '03:00'}]},
  {'day': 'Friday', 'hours': [{'start': '20:00', 'end': '04:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '18:00', 'end': '04:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '22:00', 'end': '03:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Friday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '11:00', 'end': '00:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '11:00', 'end': '00:00'}]}],
 [{'day': 'Tuesday', 'hours': [{'start': '14:00', 'end': '22:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '14:00', 'end': '22:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '14:00', 'end': '22:00'}]},
  {'day': 'Friday', 'hours': [{'start': '14:00', 'end': '22:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '14:00', 'end': '22:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '14:00', 'end': '22:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '20:30', 'end': '03:30'}]},
  {'day': 'Tuesday', 'hours': [{'start': '20:30', 'end': '03:30'}]},
  {'day': 'Wednesday', 'hours': [{'start': '20:30', 'end': '03:30'}]},
  {'day': 'Thursday', 'hours': [{'start': '20:30', 'end': '03:30'}]},
  {'day': 'Friday', 'hours': [{'start': '20:30', 'end': '03:30'}]},
  {'day': 'Saturday', 'hours': [{'start': '20:30', 'end': '03:30'}]},
  {'day': 'Sunday', 'hours': [{'start': '20:30', 'end': '03:30'}]}],
 [{'day': 'Monday', 'hours': [{'start': '06:00', 'end': '22:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '06:00', 'end': '22:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '06:00', 'end': '22:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '06:00', 'end': '22:00'}]},
  {'day': 'Friday', 'hours': [{'start': '06:00', 'end': '22:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '06:00', 'end': '22:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '06:00', 'end': '22:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '17:00', 'end': '00:30'}]},
  {'day': 'Tuesday', 'hours': [{'start': '17:00', 'end': '00:30'}]},
  {'day': 'Wednesday', 'hours': [{'start': '17:00', 'end': '00:30'}]},
  {'day': 'Thursday', 'hours': [{'start': '17:00', 'end': '00:30'}]},
  {'day': 'Friday', 'hours': [{'start': '17:00', 'end': '00:30'}]},
  {'day': 'Saturday', 'hours': [{'start': '17:00', 'end': '00:30'}]},
  {'day': 'Sunday', 'hours': [{'start': '17:00', 'end': '00:30'}]}],
 [{'day': 'Monday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Friday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '16:00', 'end': '00:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '16:00', 'end': '00:00'}]}],
 [{'day': 'Monday',
   'hours': [{'start': '13:00', 'end': '16:00'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Tuesday',
   'hours': [{'start': '13:00', 'end': '16:00'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Wednesday',
   'hours': [{'start': '13:00', 'end': '16:00'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Thursday',
   'hours': [{'start': '13:00', 'end': '16:00'},
    {'start': '20:30', 'end': '23:30'}]},
  {'day': 'Friday',
   'hours': [{'start': '13:00', 'end': '16:00'},
    {'start': '20:30', 'end': '23:30'}]}],
 [{'day': 'Monday', 'hours': [{'start': '06:00', 'end': '18:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '06:00', 'end': '18:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '06:00', 'end': '18:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '06:00', 'end': '18:00'}]},
  {'day': 'Friday', 'hours': [{'start': '06:00', 'end': '18:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '06:00', 'end': '18:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '06:00', 'end': '18:00'}]}],
 [],
 [{'day': 'Monday', 'hours': [{'start': '17:00', 'end': '01:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '17:00', 'end': '01:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '17:00', 'end': '01:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '17:00', 'end': '01:00'}]},
  {'day': 'Friday', 'hours': [{'start': '17:00', 'end': '01:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '17:00', 'end': '01:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '18:00', 'end': '02:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '18:00', 'end': '02:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '18:00', 'end': '02:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '18:00', 'end': '02:00'}]},
  {'day': 'Friday', 'hours': [{'start': '18:00', 'end': '03:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '18:00', 'end': '03:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '18:00', 'end': '02:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '20:00', 'end': '23:00'}]},
  {'day': 'Tuesday',
   'hours': [{'start': '13:30', 'end': '16:00'},
    {'start': '20:00', 'end': '23:00'}]},
  {'day': 'Thursday',
   'hours': [{'start': '13:30', 'end': '16:00'},
    {'start': '20:00', 'end': '23:00'}]},
  {'day': 'Friday',
   'hours': [{'start': '13:30', 'end': '16:00'},
    {'start': '20:00', 'end': '23:00'}]},
  {'day': 'Saturday',
   'hours': [{'start': '13:30', 'end': '16:00'},
    {'start': '20:00', 'end': '23:00'}]}],
 [{'day': 'Tuesday', 'hours': [{'start': '07:30', 'end': '20:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '07:30', 'end': '20:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '07:30', 'end': '20:00'}]},
  {'day': 'Friday', 'hours': [{'start': '07:30', 'end': '20:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '05:30', 'end': '20:30'}]},
  {'day': 'Sunday', 'hours': [{'start': '05:30', 'end': '20:30'}]}],
 [{'day': 'Monday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Friday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '07:30', 'end': '22:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '09:00', 'end': '22:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '09:00', 'end': '22:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '09:00', 'end': '22:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '09:00', 'end': '22:00'}]},
  {'day': 'Friday', 'hours': [{'start': '09:00', 'end': '22:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '09:00', 'end': '22:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '09:00', 'end': '22:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Friday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '07:30', 'end': '22:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '07:30', 'end': '22:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '06:30', 'end': '19:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '06:30', 'end': '19:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '06:30', 'end': '19:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '06:30', 'end': '19:00'}]},
  {'day': 'Friday', 'hours': [{'start': '06:30', 'end': '19:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '06:30', 'end': '19:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '06:30', 'end': '19:00'}]}],
 [],
 [{'day': 'Monday',
   'hours': [{'start': '07:00', 'end': '11:00'},
    {'start': '14:00', 'end': '16:00'}]},
  {'day': 'Tuesday',
   'hours': [{'start': '07:00', 'end': '11:00'},
    {'start': '14:00', 'end': '16:00'}]},
  {'day': 'Wednesday',
   'hours': [{'start': '07:00', 'end': '11:00'},
    {'start': '14:00', 'end': '16:00'}]},
  {'day': 'Thursday',
   'hours': [{'start': '07:00', 'end': '11:00'},
    {'start': '14:00', 'end': '16:00'}]},
  {'day': 'Friday',
   'hours': [{'start': '07:00', 'end': '11:00'},
    {'start': '14:00', 'end': '16:00'}]},
  {'day': 'Saturday',
   'hours': [{'start': '07:00', 'end': '11:00'},
    {'start': '14:00', 'end': '16:00'}]},
  {'day': 'Sunday',
   'hours': [{'start': '07:00', 'end': '11:00'},
    {'start': '14:00', 'end': '16:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '12:30', 'end': '00:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '12:30', 'end': '00:00'}]},
  {'day': 'Friday', 'hours': [{'start': '12:30', 'end': '00:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '12:30', 'end': '00:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '12:30', 'end': '00:00'}]}],
 [{'day': 'Tuesday', 'hours': [{'start': '12:30', 'end': '23:30'}]},
  {'day': 'Wednesday', 'hours': [{'start': '12:30', 'end': '23:30'}]},
  {'day': 'Thursday', 'hours': [{'start': '12:30', 'end': '23:30'}]},
  {'day': 'Friday', 'hours': [{'start': '12:30', 'end': '23:30'}]},
  {'day': 'Saturday', 'hours': [{'start': '12:30', 'end': '23:30'}]},
  {'day': 'Sunday', 'hours': [{'start': '12:30', 'end': '23:30'}]}],
 [{'day': 'Monday', 'hours': [{'start': '10:00', 'end': '16:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '10:00', 'end': '16:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '10:00', 'end': '16:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '10:00', 'end': '16:00'}]},
  {'day': 'Friday', 'hours': [{'start': '10:00', 'end': '16:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '10:00', 'end': '16:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '10:00', 'end': '16:00'}]}],
 [{'day': 'Tuesday',
   'hours': [{'start': '07:30', 'end': '11:30'},
    {'start': '13:00', 'end': '16:30'}]},
  {'day': 'Wednesday',
   'hours': [{'start': '07:30', 'end': '11:30'},
    {'start': '13:00', 'end': '16:30'}]},
  {'day': 'Thursday',
   'hours': [{'start': '07:30', 'end': '11:30'},
    {'start': '13:00', 'end': '16:30'}]},
  {'day': 'Friday',
   'hours': [{'start': '07:30', 'end': '11:30'},
    {'start': '13:00', 'end': '16:30'}]},
  {'day': 'Saturday',
   'hours': [{'start': '07:30', 'end': '11:30'},
    {'start': '13:00', 'end': '16:30'}]},
  {'day': 'Sunday',
   'hours': [{'start': '07:30', 'end': '11:30'},
    {'start': '13:00', 'end': '16:30'}]}],
 [],
 [{'day': 'Monday', 'hours': [{'start': '05:00', 'end': '21:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '05:00', 'end': '21:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '05:00', 'end': '21:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '05:00', 'end': '21:00'}]},
  {'day': 'Friday', 'hours': [{'start': '05:00', 'end': '21:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '05:00', 'end': '21:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '05:00', 'end': '21:00'}]}],
 [{'day': 'Monday', 'hours': [{'start': '09:00', 'end': '00:15'}]},
  {'day': 'Tuesday', 'hours': [{'start': '09:00', 'end': '00:15'}]},
  {'day': 'Wednesday', 'hours': [{'start': '09:00', 'end': '00:15'}]},
  {'day': 'Thursday', 'hours': [{'start': '09:00', 'end': '00:15'}]},
  {'day': 'Friday', 'hours': [{'start': '09:00', 'end': '00:45'}]},
  {'day': 'Saturday', 'hours': [{'start': '09:00', 'end': '00:45'}]},
  {'day': 'Sunday', 'hours': [{'start': '09:00', 'end': '00:15'}]}],
 [{'day': 'Monday', 'hours': [{'start': '08:00', 'end': '17:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '08:00', 'end': '17:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '08:00', 'end': '17:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '08:00', 'end': '17:00'}]},
  {'day': 'Friday', 'hours': [{'start': '08:00', 'end': '17:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '08:00', 'end': '17:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '08:00', 'end': '17:00'}]}],
 [{'day': 'Monday',
   'hours': [{'start': '05:00', 'end': '12:00'},
    {'start': '13:30', 'end': '20:30'}]},
  {'day': 'Tuesday',
   'hours': [{'start': '05:00', 'end': '12:00'},
    {'start': '13:30', 'end': '20:30'}]},
  {'day': 'Wednesday',
   'hours': [{'start': '05:00', 'end': '12:00'},
    {'start': '13:30', 'end': '20:30'}]},
  {'day': 'Thursday',
   'hours': [{'start': '05:00', 'end': '12:00'},
    {'start': '13:30', 'end': '20:30'}]},
  {'day': 'Friday',
   'hours': [{'start': '05:00', 'end': '12:00'},
    {'start': '13:30', 'end': '20:30'}]},
  {'day': 'Saturday',
   'hours': [{'start': '05:00', 'end': '12:00'},
    {'start': '13:30', 'end': '20:30'}]},
  {'day': 'Sunday',
   'hours': [{'start': '05:00', 'end': '12:00'},
    {'start': '13:30', 'end': '20:30'}]}],
 [],
 [],
 [{'day': 'Monday', 'hours': [{'start': '04:30', 'end': '17:30'}]},
  {'day': 'Tuesday', 'hours': [{'start': '04:30', 'end': '17:30'}]},
  {'day': 'Wednesday', 'hours': [{'start': '04:30', 'end': '17:30'}]},
  {'day': 'Thursday', 'hours': [{'start': '04:30', 'end': '17:30'}]},
  {'day': 'Friday', 'hours': [{'start': '04:30', 'end': '17:30'}]},
  {'day': 'Saturday', 'hours': [{'start': '04:30', 'end': '17:30'}]},
  {'day': 'Sunday', 'hours': [{'start': '04:30', 'end': '17:30'}]}],
 [],
 [],
 [{'day': 'Monday',
   'hours': [{'start': '13:00', 'end': '18:00'},
    {'start': '19:30', 'end': '23:30'}]},
  {'day': 'Wednesday',
   'hours': [{'start': '13:00', 'end': '18:00'},
    {'start': '19:30', 'end': '23:30'}]},
  {'day': 'Thursday',
   'hours': [{'start': '13:00', 'end': '18:00'},
    {'start': '19:30', 'end': '23:30'}]},
  {'day': 'Friday',
   'hours': [{'start': '13:00', 'end': '18:00'},
    {'start': '19:30', 'end': '23:30'}]},
  {'day': 'Saturday',
   'hours': [{'start': '13:00', 'end': '18:00'},
    {'start': '19:30', 'end': '23:30'}]},
  {'day': 'Sunday',
   'hours': [{'start': '13:00', 'end': '18:00'},
    {'start': '19:30', 'end': '23:30'}]}],
 [{'day': 'Monday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Tuesday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Wednesday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Thursday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Friday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Saturday', 'hours': [{'start': '00:00', 'end': '23:59'}]},
  {'day': 'Sunday', 'hours': [{'start': '00:00', 'end': '23:59'}]}],
 [{'day': 'Monday', 'hours': [{'start': '08:00', 'end': '05:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '08:00', 'end': '05:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '08:00', 'end': '05:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '08:00', 'end': '05:00'}]},
  {'day': 'Friday', 'hours': [{'start': '08:00', 'end': '05:00'}]}],
 [],
 [],
 [{'day': 'Monday', 'hours': [{'start': '12:00', 'end': '00:00'}]},
  {'day': 'Tuesday', 'hours': [{'start': '12:00', 'end': '00:00'}]},
  {'day': 'Wednesday', 'hours': [{'start': '12:00', 'end': '00:00'}]},
  {'day': 'Thursday', 'hours': [{'start': '12:00', 'end': '00:00'}]},
  {'day': 'Friday', 'hours': [{'start': '12:00', 'end': '01:00'}]},
  {'day': 'Saturday', 'hours': [{'start': '12:00', 'end': '01:00'}]},
  {'day': 'Sunday', 'hours': [{'start': '12:00', 'end': '00:00'}]}],

In [79]:
len(clean_opening_hours_special(result))

1454

In [80]:
file_path = os.path.join(os.getcwd(), "data/data_final.csv")
df = pd.read_csv(file_path, encoding="utf-8")
df.head(1)

,id,name,address,lat,lon,poi_type,avg_stars,total_reviews,stay_time,normalize_stars_reviews,crowd,offerings,atmosphere,highlights,dining_options,children,accessibility,popular_for
0,0f9d2009-9436-46a4-b354-b0261898a39e,The Pub Coffee - Beer & Cocktail,"18A17 Tăng Nhơn Phú, Phước Long B, Quận 9, Thà...",10.829481,106.773785,"Cafe,Bar",4.9,181,30,0.755,Groups,"Alcohol, Beer, Cocktails, Coffee, Hard liquor","Casual, Cozy","Great beer selection, Great coffee, Live music...",Table service,NaN,NaN,NaN

In [82]:
df['opening_hours'] = clean_opening_hours_special(result)

In [83]:
df.head(1)

,id,name,address,lat,lon,poi_type,avg_stars,total_reviews,stay_time,normalize_stars_reviews,crowd,offerings,atmosphere,highlights,dining_options,children,accessibility,popular_for,opening_hours
0,0f9d2009-9436-46a4-b354-b0261898a39e,The Pub Coffee - Beer & Cocktail,"18A17 Tăng Nhơn Phú, Phước Long B, Quận 9, Thà...",10.829481,106.773785,"Cafe,Bar",4.9,181,30,0.755,Groups,"Alcohol, Beer, Cocktails, Coffee, Hard liquor","Casual, Cozy","Great beer selection, Great coffee, Live music...",Table service,NaN,NaN,NaN,"[{'day': 'Monday', 'hours': [{'start': '00:00'..."

In [ ]:
df.to_csv("data/new_data_final.csv", index=False)

# Test time bằng python

In [52]:
from datetime import datetime

now = datetime.now()

# Lấy giờ và phút
gio_phut = now.strftime("%H:%M")

# Lấy thứ (tiếng Anh)
thu = now.strftime("%A")

print("Thứ:", thu)
print("Giờ và phút:", gio_phut)

Thứ: Friday
Giờ và phút: 15:16

# Clean opening_hours

In [1]:
opening_hours = [{'day': 'Monday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Tuesday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Wednesday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Thursday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Friday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Saturday', 'hours': [{'start': '00:00', 'end': '23:59'}]}, {'day': 'Sunday', 'hours': [{'start': '00:00', 'end': '23:59'}]}]